
export interface NewsUpdate {
  id: string;
  date: string;
  company: string;
  title: string;
  description: string;
  link: string;
  country: '中国' | '美国' | '法国' | '加拿大' | '韩国' | '英国' | '俄罗斯' | '德国' | '印度' | '日本';
  category: 'LLM' | 'Image Generation' | 'Audio' | 'Developer Tools' | 'Platform' | 'Search' | 'Research';
  pricing: '免费' | '付费' | '开源' | '免费增值' | '商业' | '研究';
  price?: string;
  version?: string;
  parentCompany?: string;
  type?: string;
  status?: 'Active' | 'Deprecated';
}

export const companyUrls: Record<string, string> = {
  "OpenAI": "https://openai.com",
  "Mistral AI": "https://mistral.ai",
  "Cohere": "https://cohere.com",
  "Perplexity": "https://perplexity.ai",
  "Zhipu AI": "https://www.zhipuai.cn",
  "Baidu": "https://www.baidu.com",
  "Stability AI": "https://stability.ai",
  "Sberbank": "https://www.sberbank.com",
  "Yandex": "https://yandex.com",
  "VK": "https://vk.company",
  "NtechLab": "https://ntechlab.com",
  "VisionLabs": "https://visionlabs.ai",
  "Databricks": "https://www.databricks.com",
  "Alibaba Cloud": "https://www.alibabacloud.com",
  "Tencent": "https://www.tencent.com",
  "Moonshot AI": "https://moonshot.cn",
  "Anthropic": "https://www.anthropic.com",
  "Google AI": "https://ai.google",
  "Microsoft AI": "https://www.microsoft.com/en-us/ai",
  "NVIDIA": "https://www.nvidia.com",
  "Amazon Web Services": "https://aws.amazon.com",
  "Meta AI": "https://ai.meta.com",
  "IBM": "https://www.ibm.com",
  "Scale AI": "https://scale.com",
  "Palantir": "https://www.palantir.com",
  "xAI": "https://x.ai",
  "Aleph Alpha": "https://aleph-alpha.com",
  "DeepL": "https://www.deepl.com",
  "Mech-Mind Robotics": "https://www.mech-mind.com",
  "Krutrim AI": "https://olakrutrim.com",
  "Sarvam AI": "https://sarvam.ai",
  "Darktrace": "https://darktrace.com",
  "Synthesia": "https://www.synthesia.io",
  "BenevolentAI": "https://www.benevolent.com",
  "Dataiku": "https://www.dataiku.com",
  "LightOn": "https://www.lighton.ai",
  "Algolia": "https://www.algolia.com",
  "Doosan Robotics": "https://www.doosanrobotics.com",
  "Lunit": "https://www.lunit.io",
  "Upstage": "https://upstage.ai",
  "Coveo": "https://www.coveo.com",
  "SenseTime": "https://www.sensetime.com",
  "iFlytek": "https://www.iflytek.com",
  "Baichuan Intelligent Technology": "https://www.baichuan-ai.com",
  "DeepSeek": "https://www.deepseek.com",
  "ByteDance": "https://www.bytedance.com",
  "Huawei": "https://www.huawei.com",
  "Stanford University": "https://www.stanford.edu",
  "CoreWeave": "https://www.coreweave.com",
  "Anduril": "https://www.anduril.com",
  "Figure AI": "https://www.figure.ai",
  "Crusoe": "https://crusoe.ai",
  "Harvey": "https://www.harvey.ai",
  "Runway": "https://runwayml.com",
  "Skild AI": "https://www.skild.ai",
  "Writer": "https://writer.com",
  "Helsing": "https://helsing.ai",
  "KUKA": "https://www.kuka.com",
  "Franka Robotics": "https://www.franka.de",
  "SAP": "https://www.sap.com",
  "Bosch": "https://www.bosch.com",
  "Photoroom": "https://www.photoroom.com",
  "Naver": "https://www.navercorp.com",
  "Kakao Brain": "https://www.kakaobrain.com",
  "LG AI Research": "https://www.lgresearch.ai",
  "SK Telecom": "https://www.sktelecom.com",
  "Rebellion": "https://rebellions.ai",
  "Moloco": "https://www.moloco.com",
  "SELVAS AI": "https://www.selvasai.com",
  "Supertone": "https://supertone.ai",
  "Ada": "https://www.ada.cx",
  "Deep Genomics": "https://www.deepgenomics.com",
  "Sanctuary AI": "https://www.sanctuary.ai",
  "Tenstorrent": "https://tenstorrent.com",
  "CoRover.ai": "https://www.corover.ai",
  "Wayve": "https://wayve.ai",
  "Preferred Networks": "https://www.preferred.jp",
  "Sakana AI": "https://sakana.ai",
  "Mujin": "https://www.mujin-corp.com",
  "Rinna": "https://rinna.co.jp",
  "Toyota": "https://global.toyota",
  "Cinnamon AI": "https://cinnamon.ai",
  "LeapMind": "https://leapmind.io",
  "NEC": "https://www.nec.com",
  "Mitsubishi Electric": "https://www.mitsubishielectric.com",
  "Hitachi": "https://www.hitachi.com",
  "ElevenLabs": "https://elevenlabs.io",
  "Anysphere": "https://cursor.sh",
  "Hume AI": "https://www.hume.ai",
  "Soundful": "https://soundful.com",
  "Cerebras Systems": "https://www.cerebras.net",
  "Forethought": "https://forethought.ai",
  "Nextera Robotics": "https://www.nexterarobotics.com",
  "Midjourney": "https://www.midjourney.com",
  "Uizard": "https://uizard.io",
  "DeepNight": "https://www.deepnight.ai",
  "Atla": "https://www.atla.ai",
  "Parloa": "https://parloa.com",
  "cartagon.ai": "https://cartagon.com",
  "Langdock": "https://www.langdock.com",
  "PIYA AI": "https://www.piya.ai",
  "Capsula": "https://capsula.ai",
  "Stardawn AI": "https://stardawn.ai", // Assuming a domain
  "AIPort": "https://airport-group.de", // Assuming a domain
  "H Company": "https://www.h.ai",
  "Poolside": "https://poolside.ai",
  "Adaptive ML": "https://adaptive-ml.com",
  "Waabi": "https://waabi.ai",
  "Turing Co., Ltd.": "https://www.turing-motors.com",
  "EDGEMATRIX": "https://www.edgematrix.com",
  "fastctl.ai": "https://fastctl.ai",
  "Graphcore": "https://www.graphcore.ai",
  "Oxa": "https://oxa.ai",
  "Fetch.ai": "https://fetch.ai"
};

export const newsUpdates: NewsUpdate[] = [
  {
    id: "1",
    title: "GPT-5 多模态模型",
    description: "OpenAI的旗舰多模态模型，可以实时对音频、视觉和文本进行推理，并提供针对性能和延迟优化的版本。",
    company: "OpenAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    price: "Plus: $20/月",
    version: "GPT-5",
    date: "2025-08-07",
    link: "https://openai.com/index/introducing-gpt-5/",
    status: "Active"
  },
  {
    id: "226",
    title: "ChatGPT 对话式AI",
    description: "一个基于GPT系列模型构建的对话式AI，能够以自然、类人的方式与用户互动，广泛用于问答、写作、摘要和创意生成等多种任务。",
    company: "OpenAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    price: "Plus: $20/月",
    version: "GPT-5 powered",
    date: "2022-11-30",
    link: "https://chat.openai.com/",
    status: "Active"
  },
  {
    id: "200",
    title: "DALL-E 3 图像生成模型",
    description: "OpenAI的旗舰图像生成模型，能够根据文本描述创建高度详细和准确的图像，深度集成于ChatGPT和API中。",
    company: "OpenAI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    price: "Plus: $20/月",
    version: "DALL-E 3",
    date: "2023-09-20",
    link: "https://openai.com/dall-e-3/",
    status: "Active"
  },
  {
    id: "201",
    title: "Sora 文生视频模型",
    description: "一款能够根据文本指令创建长达一分钟的逼真和富有想象力视频的AI模型，代表了视频生成技术的重大突破。",
    company: "OpenAI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "研究",
    version: "Sora",
    date: "2024-02-15",
    link: "https://openai.com/sora",
    status: "Active"
  },
  {
    id: "202",
    title: "Whisper 语音识别模型",
    description: "一个开源的、鲁棒的语音识别模型，能够将多种语言的语音转录为文本，准确性达到人类水平。",
    company: "OpenAI",
    country: "美国",
    category: "Audio",
    type: "Product",
    pricing: "开源",
    version: "Whisper",
    date: "2022-09-21",
    link: "https://github.com/openai/whisper",
    status: "Active"
  },
  {
    id: "9",
    title: "Mixtral 8x7B 大模型",
    description: "一款高性能的开源稀疏混合专家（SMoE）模型，通过更少的计算资源实现了卓越的性能，在开源社区中广受欢迎。",
    company: "Mistral AI",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Mixtral 8x7B",
    date: "2023-12-09",
    link: "https://github.com/mistralai/mistral-src",
    status: "Active"
  },
  {
    id: "209",
    title: "Mistral Large 模型",
    description: "Mistral AI的旗舰大语言模型，具备顶级的推理能力，支持英语、法语、西班牙语、德语和意大利语，并通过La Plateforme平台提供服务。",
    company: "Mistral AI",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "Mistral Large 3.1",
    date: "2025-08-12",
    link: "https://mistral.ai/news/mistral-large-2508/",
    status: "Active"
  },
  {
    id: "10",
    title: "Embed v3 语义引擎",
    description: "Cohere的最新语义引擎，支持千亿级数据实时检索，显著提升了金融文档等领域的解析效率。",
    company: "Cohere",
    country: "加拿大",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    price: "按需付费",
    version: "Embed v3",
    date: "2023-11-01",
    link: "https://cohere.com/models/embed",
    status: "Active"
  },
  {
    id: "214",
    title: "Command R+ 大模型",
    description: "Cohere的旗舰级大语言模型，为企业级应用设计，具备强大的多语言能力、检索增强生成（RAG）和工具使用功能。",
    company: "Cohere",
    country: "加拿大",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "Command A",
    date: "2025-03-01",
    link: "https://cohere.com/blog/command-a",
    status: "Active"
  },
  {
    id: "12",
    title: "Perplexity AI 搜索引擎",
    description: "一个由大型语言模型驱动的对话式搜索引擎，提供准确和上下文相关的答案，并支持引用来源。",
    company: "Perplexity",
    country: "美国",
    category: "Search",
    type: "Service",
    pricing: "免费增值",
    price: "Pro: $20/月",
    version: "",
    date: "2022-08-01",
    link: "https://www.perplexity.ai/",
    status: "Active"
  },
  {
    id: "14",
    title: "智谱清言 对话产品",
    description: "面向C端的对话式AI助手，基于GLM大模型构建，提供智能问答和内容创作服务。",
    company: "Zhipu AI",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    price: "Pro: ¥25/月",
    version: "智谱清言",
    date: "2023-08-01",
    link: "https://www.zhipuai.cn/",
    status: "Active"
  },
  {
    id: "218",
    title: "GLM-4.5 大模型",
    description: "智谱AI的旗舰级基座大模型，支持128k长上下文，具备多模态能力，并在中文对齐方面表现出色。",
    company: "Zhipu AI",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "GLM-4.5",
    date: "2025-04-26",
    link: "https://www.zhipuai.cn/glm-4.5",
    status: "Active"
  },
  {
    id: "219",
    title: "CogView 文生图模型",
    description: "智谱AI推出的文生图模型，能够根据文本描述生成高质量的图像，是GLM多模态能力的重要组成部分。",
    company: "Zhipu AI",
    country: "中国",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "CogView 3",
    date: "2024-01-16",
    link: "https://www.zhipuai.cn/gallery",
    status: "Active"
  },
  {
    id: "212",
    title: "文心大模型 (ERNIE Foundation Models)",
    description: "百度自主研发的产业级知识增强大模型，涵盖了从自然语言处理到多模态理解的广泛能力，为各行各业提供AI基础能力。",
    company: "Baidu",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "ERNIE 4.5",
    date: "2025-03-16",
    link: "https://wenxin.baidu.com/ebh/index",
    status: "Active"
  },
  {
    id: "221",
    title: "文心一格 (ERNIE-ViLG)",
    description: "百度推出的AI艺术和创意辅助平台，能够根据文本描述生成多样风格的图片，支持从风景画到概念艺术的广泛创作。",
    company: "Baidu",
    country: "中国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    price: "Pro: ¥49/月",
    version: "",
    date: "2022-08-19",
    link: "https://yige.baidu.com/",
    status: "Active"
  },
  {
    id: "16",
    title: "Stable Diffusion 3.5 图像生成模型",
    description: "Stability AI的旗舰图像生成模型，最新版本支持4K分辨率，在开源社区的调用量已超过10亿次。",
    company: "Stability AI",
    country: "英国",
    category: "Image Generation",
    type: "Product",
    pricing: "开源",
    version: "3.5",
    date: "2025-06-24",
    link: "https://github.com/Stability-AI/generative-models",
    status: "Active"
  },
  {
    id: "229",
    title: "Stable Audio 2.5",
    description: "Stability AI推出的AI音频生成模型，能够根据文本提示创作高质量、结构完整的完整音轨，时长可达3分钟，并支持音频到音频的转换。",
    company: "Stability AI",
    country: "英国",
    category: "Audio",
    type: "Product",
    pricing: "免费增值",
    price: "Pro: $11.99/月",
    version: "2.5",
    date: "2025-05-14",
    link: "https://stability.ai/stable-audio-2.5",
    status: "Active"
  },
  {
    id: "17",
    title: "GigaChat 2.0 大模型",
    description: "Sberbank的旗舰大语言模型，在俄语任务上对标GPT-4，展示了强大的本地化语言能力。",
    company: "Sberbank",
    country: "俄罗斯",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "2.0",
    date: "2025-03-13",
    link: "https://www.sberbank.com/sberchat/gigachat-2.0",
    status: "Active"
  },
  {
    id: "166",
    title: "YandexGPT 3 大模型",
    description: "Yandex的旗舰级大语言模型，在俄语和多语言任务上表现出色，并推出了针对不同场景优化的Pro、Lite和Summary版本。",
    company: "Yandex",
    country: "俄罗斯",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "3",
    date: "2024-02-15",
    link: "https://cloud.yandex.com/en/services/yandexgpt",
    status: "Active"
  },
  {
    id: "167",
    title: "VK AI 大模型",
    description: "俄罗斯科技巨头VK正在为其庞大的社交和内容生态系统开发自研的大型AI模型。",
    company: "VK",
    country: "俄罗斯",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    date: "2024-09-01",
    link: "https://vk.company/en/",
    status: "Active"
  },
  {
    id: "168",
    title: "FindFace Multi 平台",
    description: "一个高精度的多目标面部识别平台，广泛应用于公共安全和商业领域，能够实时识别和分析视频流中的人脸。",
    company: "NtechLab",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-11-01",
    link: "https://ntechlab.com/",
    status: "Active"
  },
  {
    id: "169",
    title: "Luna Platform",
    description: "一个全面的计算机视觉和视频分析平台，提供面部识别、物体识别和行为分析等功能，服务于金融、零售和智慧城市等多个行业。",
    company: "VisionLabs",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-10-01",
    link: "https://visionlabs.ai/",
    status: "Active"
  },
  {
    id: "18",
    title: "DBRX 大模型",
    description: "一款拥有 132B 参数的 MoE 架构开源大语言模型，在多项基准测试中表现出色。",
    company: "Databricks",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "DBRX",
    date: "2024-03-27",
    link: "https://github.com/databricks/dbrx",
    status: "Active"
  },
  {
    id: "213",
    title: "Mosaic AI 平台",
    description: "一个统一的平台，用于构建、部署和监控生产级的生成式AI应用，深度集成了数据处理和模型治理能力。",
    company: "Databricks",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-06-28",
    link: "https://www.databricks.com/product/mosaic-ai",
    status: "Active"
  },
  {
    id: "20",
    title: "通义万相 视频生成",
    description: "一款先进的AI视频生成模型，能够根据文本或图像输入创造出富有想象力的高清视频内容，其开源版本Wan2.2-VACE推动了社区创新。",
    company: "Alibaba Cloud",
    country: "中国",
    category: "Image Generation",
    type: "Product",
    pricing: "开源",
    version: "Wan2.2-VACE",
    date: "2025-06-30",
    link: "https://github.com/modelscope/wan-2",
    status: "Active"
  },
  {
    id: "227",
    title: "通义千问 (Qwen)",
    description: "阿里巴巴达摩院自研的通义大模型，提供强大的通用语言能力，支持多语言、长文本理解，并有多个开源版本（如Qwen3）在社区广受欢迎。",
    company: "Alibaba Cloud",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Qwen3",
    date: "2025-05-04",
    link: "https://github.com/QwenLM/Qwen",
    status: "Active"
  },
  {
    id: "21",
    title: "腾讯混元大模型 T1",
    description: "腾讯发布的万亿参数大语言模型，已升级至T1版本，并在2024年推出通用大模型产品“腾讯元宝”，深度融入微信生态。",
    company: "Tencent",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    date: "2024-06-01",
    link: "https://hunyuan.tencent.com/",
    status: "Active"
  },
  {
    id: "22",
    title: "Kimi 智能助手 (200万字上下文)",
    description: "月之暗面推出的Kimi智能助手，以其突破性的200万字超长无损上下文窗口而闻名，能够高效处理和理解大规模文档。",
    company: "Moonshot AI",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    price: "Pro: ¥20/月",
    version: "K2",
    date: "2025-07-14",
    link: "https://kimi.moonshot.cn/",
    status: "Active"
  },
  {
    id: "29",
    title: "Claude 4 Opus",
    description: "Anthropic的旗舰模型，在高度复杂的任务上提供顶尖性能，为策略、研发和复杂工作流设定了新标准。",
    company: "Anthropic",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "Pro: $20/月",
    version: "Claude 4 Opus",
    date: "2025-05-22",
    link: "https://www.anthropic.com/product",
    status: "Active"
  },
  {
    id: "210",
    title: "Claude 4 Sonnet",
    description: "Anthropic的中端模型，在性能和成本效益上取得平衡，并引入了动态知识图谱构建等新功能。",
    company: "Anthropic",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "Claude 4 Sonnet",
    date: "2025-05-22",
    link: "https://www.anthropic.com/news/claude-4-family",
    status: "Active"
  },
  {
    id: "211",
    title: "Claude 4 Haiku",
    description: "Anthropic最快、最紧凑的模型，为需要实时响应的简单查询和任务提供接近即时的响应速度，例如实时聊天和内容审核。",
    company: "Anthropic",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "Claude 4 Haiku",
    date: "2025-05-22",
    link: "https://www.anthropic.com/news/claude-4-family",
    status: "Active"
  },
  {
    id: "32",
    title: "Gemini 2.5 (Flash & Pro)",
    description: "谷歌的下一代旗舰多模态模型，具备百万级Token的超长上下文窗口、多模态推理能力，并提供针对速度和效率优化的Flash版本。",
    company: "Google AI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    price: "Pro: $20/月",
    version: "2.5",
    date: "2025-08-12",
    link: "https://deepmind.google/technologies/gemini/flash/",
    status: "Active"
  },
  {
    id: "36",
    title: "Jules 编码助手",
    description: "一款集成在开发环境中的AI编码助手，旨在帮助开发者更快地编写、调试和优化代码。",
    company: "Google AI",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "免费增值",
    date: "2024-05-14",
    link: "https://deepmind.google/discover/blog/new-models-and-developer-tools-to-build-with-gemini-and-google-ai/",
    status: "Active"
  },
  {
    id: "111",
    title: "AlphaFold 3",
    description: "由Google DeepMind与Isomorphic Labs联合发布，能够精准预测蛋白质与包括配体、离子在内的多种分子间的相互作用，加速药物发现。",
    company: "Google AI",
    country: "美国",
    category: "Research",
    type: "Research",
    pricing: "研究",
    version: "3",
    date: "2024-05-08",
    link: "https://deepmind.google/discover/blog/alphafold-3-predicts-the-structure-and-interactions-of-all-of-lifes-molecules/",
    status: "Active"
  },
  {
    id: "207",
    title: "Imagen 3 图像生成模型",
    description: "谷歌最先进的文生图模型，能够生成逼真、细节丰富、且深刻理解自然语言提示的图像。",
    company: "Google AI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "Imagen 3",
    date: "2024-05-14",
    link: "https://deepmind.google/technologies/imagen/",
    status: "Active"
  },
  {
    id: "215",
    title: "Veo 文生视频模型",
    description: "谷歌最先进的文生视频模型，能够生成长达一分钟以上的高清1080p视频，并能精准理解电影术语，创造出连贯、逼真的视觉效果。",
    company: "Google AI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "研究",
    version: "",
    date: "2024-05-14",
    link: "https://deepmind.google/technologies/veo/",
    status: "Active"
  },
  {
    id: "216",
    title: "Project Astra 多模态AI助手",
    description: "谷歌对未来AI助手的愿景，一个实时的、多模态的通用AI智能体，能够通过摄像头和麦克风理解并响应复杂的环境和对话。",
    company: "Google AI",
    country: "美国",
    category: "Research",
    type: "Research",
    pricing: "研究",
    version: "",
    date: "2024-05-14",
    link: "https://deepmind.google/technologies/gemini/project-astra/",
    status: "Active"
  },
  {
    id: "217",
    title: "Vertex AI 机器学习平台",
    description: "谷歌云的统一机器学习平台，帮助开发者构建、部署和扩展AI模型，提供了对Gemini等基础模型的访问和工具支持。",
    company: "Google AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-01-01",
    link: "https://cloud.google.com/vertex-ai",
    status: "Active"
  },
  {
    id: "38",
    title: "Microsoft 365 Copilot",
    description: "微软的AI助手，已集成到Word、Excel和Teams等Microsoft 365应用中，旨在提高工作场所的生产力和创造力。",
    company: "Microsoft AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    price: "企业版: $30/用户/月",
    version: "",
    date: "2023-09-26",
    link: "https://www.microsoft.com/en-us/microsoft-365/blog/2023/03/16/introducing-microsoft-365-copilot-your-copilot-for-work/",
    status: "Active"
  },
  {
    id: "204",
    title: "Phi-3.5 小型语言模型 (SLM)",
    description: "微软推出的一系列高性能、低成本的小型语言模型（SLM），专为在资源受限的环境（如移动设备）上高效运行而设计。",
    company: "Microsoft AI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Phi-3.5",
    date: "2025-08-22",
    link: "https://github.com/microsoft/phi",
    status: "Active"
  },
  {
    id: "205",
    title: "GitHub Copilot 编程助手",
    description: "由GitHub和OpenAI共同开发的AI编程助手，能够实时提供代码建议、补全和生成，深度集成于主流IDE中，极大地提升了开发效率。",
    company: "Microsoft AI",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    price: "个人: $10/月, 企业: $19/用户/月",
    version: "",
    date: "2023-01-01",
    link: "https://github.com/features/copilot",
    status: "Active"
  },
  {
    id: "206",
    title: "Microsoft Designer 图像创作工具",
    description: "一款由DALL-E 3驱动的AI图形设计应用，帮助用户通过简单的文本描述快速创建高质量的社交媒体帖子、邀请函、海报和设计。",
    company: "Microsoft AI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    date: "2023-04-12",
    link: "https://designer.microsoft.com/",
    status: "Active"
  },
  {
    id: "222",
    title: "Microsoft Copilot",
    description: "微软的通用AI助手，深度集成于Windows、Edge浏览器和Bing搜索中，提供对话式应答、内容生成和任务辅助功能。",
    company: "Microsoft AI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    price: "Pro: $20/月",
    version: "",
    date: "2023-11-15",
    link: "https://copilot.microsoft.com/",
    status: "Active"
  },
  {
    id: "223",
    title: "Azure AI Platform",
    description: "微软的企业级AI服务平台，提供对OpenAI模型和Phi等自研模型的访问，以及用于构建、部署和管理AI应用的全套工具。",
    company: "Microsoft AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    price: "按需付费",
    version: "",
    date: "2023-05-23",
    link: "https://azure.microsoft.com/en-us/solutions/ai",
    status: "Active"
  },
  {
    id: "41",
    title: "Blackwell GPU 架构",
    description: "新一代GPU架构，为万亿参数级别的大型语言模型提供实时生成式AI能力，显著提升了计算性能和能效。",
    company: "NVIDIA",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2024-03-18",
    link: "https://nvidianews.nvidia.com/news/nvidia-blackwell-platform-arrives-to-power-a-new-era-of-computing",
    status: "Active"
  },
  {
    id: "224",
    title: "NVIDIA NIM 推理微服务",
    description: "一套优化的推理微服务，用于大规模部署AI模型，提供预构建的容器和标准API，支持来自NVIDIA、合作伙伴和开源社区的模型。",
    company: "NVIDIA",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    date: "2024-03-18",
    link: "https://nvidianews.nvidia.com/news/nvidia-launches-generative-ai-microservices-for-developers-to-create-and-deploy-applications-on-their-platforms",
    status: "Active"
  },
  {
    id: "44",
    title: "Amazon Bedrock",
    description: "一个用于构建生成式 AI 应用的托管服务，提供来自领先AI公司的多种基础模型选择，包括 Anthropic、Cohere 等。",
    company: "Amazon Web Services",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    price: "按需付费",
    version: "",
    date: "2023-09-28",
    link: "https://aws.amazon.com/bedrock/",
    status: "Active"
  },
  {
    id: "208",
    title: "Amazon Q 商业版助手",
    description: "一款为企业打造的生成式AI助手，能够回答问题、生成内容，并根据企业数据和系统采取行动，旨在提高员工生产力。",
    company: "Amazon Web Services",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    price: "$20/用户/月",
    version: "",
    date: "2024-04-30",
    link: "https://aws.amazon.com/q/",
    status: "Active"
  },
  {
    id: "48",
    title: "Meta AI 助手",
    description: "深度集成于Facebook、Instagram、WhatsApp和Messenger等应用的AI助手，提供对话、内容创作和实时信息服务。",
    company: "Meta AI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    date: "2023-09-25",
    link: "https://ai.meta.com/",
    status: "Active"
  },
  {
    id: "203",
    title: "Llama 3.2 开源大模型",
    description: "Meta推出的下一代开源大语言模型，提供8B和70B两种尺寸，在推理、代码生成和指令遵循方面表现卓越。",
    company: "Meta AI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Llama 3.2",
    date: "2025-09-25",
    link: "https://github.com/meta-llama/llama3",
    status: "Active"
  },
  {
    id: "220",
    title: "Imagine with Meta AI",
    description: "一个由Meta的Emu模型驱动的独立图像生成工具，允许用户通过文本提示创建高分辨率的图像。",
    company: "Meta AI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    date: "2023-12-06",
    link: "https://imagine.meta.com/",
    status: "Active"
  },
  {
    id: "51",
    title: "watsonx 平台",
    description: "一个为企业提供支持的企业级AI和数据平台，用于训练、验证、调整和部署AI模型，包括watsonx.ai、watsonx.data和watsonx.governance。",
    company: "IBM",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-05-09",
    link: "https://www.ibm.com/watsonx",
    status: "Active"
  },
  {
    id: "56",
    title: "Enterprise Generative AI Platform",
    description: "一个为企业提供支持的平台，用于基础模型的微调、安全保护和部署，确保AI应用的可靠性和可扩展性。",
    company: "Scale AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-12-05",
    link: "https://scale.com/",
    status: "Active"
  },
  {
    id: "61",
    title: "AIP (人工智能平台)",
    description: "一个将大型语言模型（LLM）与企业私有网络集成的平台，专为政府和商业客户设计，支持在安全环境中进行决策和运营。",
    company: "Palantir",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "AIP",
    date: "2023-04-27",
    link: "https://www.palantir.com/platforms/aip/",
    status: "Active"
  },
  {
    id: "63",
    title: "Grok-4 大模型",
    description: "xAI的旗舰大语言模型，具备长上下文处理能力和先进的推理功能，并能通过X平台实时访问信息。",
    company: "xAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "Premium+ Plan",
    version: "4",
    date: "2025-07-09",
    link: "https://x.ai/blog/grok-4",
    status: "Active"
  },
  {
    id: "230",
    title: "Grok-1.5V 多模态模型",
    description: "Grok-1.5的升级版，增加了处理视觉信息的能力，能够理解图像、文档和图表，在真实世界空间理解基准测试中表现出色。",
    company: "xAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "1.5V",
    date: "2024-04-26",
    link: "https://x.ai/blog/grok-1.5v",
    status: "Active"
  },
  {
    id: "231",
    title: "Grok-2 图像生成模型",
    description: "Grok模型的最新版本，首次引入了由自研的Aurora模型驱动的图像生成能力，可供X Premium订阅用户使用。",
    company: "xAI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    version: "2",
    date: "2024-08-08",
    link: "https://x.ai/blog/grok-2",
    status: "Active"
  },
  {
    id: "232",
    title: "PromptIDE 开发环境",
    description: "一个用于提示工程和可解释性研究的集成开发环境，提供SDK和工具来加速复杂提示技术的开发和分析。",
    company: "xAI",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "研究",
    version: "",
    date: "2023-11-08",
    link: "https://x.ai/blog/prompt-ide",
    status: "Active"
  },
  {
    id: "233",
    title: "Grok 对话式AI",
    description: "xAI推出的首款AI聊天机器人，旨在提供幽默、机智的回答，并以“最大化真相寻求”为目标，设计灵感来源于《银河系漫游指南》。",
    company: "xAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "Premium+ Plan",
    version: "",
    date: "2023-11-04",
    link: "https://grok.x.ai/",
    status: "Active"
  },
  {
    id: "234",
    title: "Grok-1 开源大模型",
    description: "一个拥有3140亿参数的开源大型语言模型，采用专家混合（MoE）架构，具备强大的语言理解和生成能力。",
    company: "xAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Grok-1",
    date: "2024-03-17",
    link: "https://github.com/xai-org/grok-1",
    status: "Active"
  },
  {
    id: "235",
    title: "Grok-4 大模型",
    description: "被誉为“地表最强 AI”，具备强大的逻辑推理、编码和创意协作能力，支持多种高级功能模式。",
    company: "xAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "Premium+ Plan",
    version: "4",
    date: "2025-07-09",
    link: "https://x.ai/",
    status: "Active"
  },
  {
    id: "236",
    title: "Grok-3 Mini 大模型",
    description: "Grok-3的紧凑版本，专注于快速、成本效益高的任务处理，在STEM、数学和编码任务中表现优异。",
    company: "xAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "3 Mini",
    date: "2025-04-01",
    link: "https://x.ai/",
    status: "Deprecated"
  },
  {
    id: "237",
    title: "Aurora 图像生成模型",
    description: "xAI开发的专有自回归图像生成模型，支持多模态理解、编辑和高品质图像生成，是Grok-2图像生成功能的核心。",
    company: "xAI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    version: "Aurora",
    date: "2024-08-08",
    link: "https://x.ai/blog/grok-2",
    status: "Active"
  },
  {
    id: "238",
    title: "Grok Studio",
    description: "一个强大的开发环境，支持代码执行、生成文档、报告及网页游戏，并与Google云端硬盘集成以方便协作。",
    company: "xAI",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2025-04-01",
    link: "https://x.ai/",
    status: "Active"
  },
  {
    id: "239",
    title: "xAI API",
    description: "允许开发者访问xAI的基础模型，支持多区域低延迟推理、功能调用和自定义系统提示词，并集成了实时网络搜索功能。",
    company: "xAI",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    price: "按需付费",
    version: "",
    date: "2024-10-01",
    link: "https://x.ai/api",
    status: "Active"
  },
  {
    id: "78",
    title: "PhariaAI 企业级AI操作系统",
    description: "一个企业级的生成式AI操作系统，支持混合执行、可解释性和合规性，专为政府和企业级应用设计。",
    company: "Aleph Alpha",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-01-01",
    link: "https://aleph-alpha.com/aleph-alpha-launches-phariaai-the-enterprise-grade-operating-system-for-generative-ai-combining-future-proof-sovereign-design-with-llm-explainability-and-compliance/",
    status: "Active"
  },
  {
    id: "79",
    title: "DeepL Write Pro",
    description: "一款专为企业用户设计的AI写作助手，提供风格和语气的定制化建议，已扩展支持西班牙语、法语、意大利语和葡萄牙语，持续提升全球商业沟通效率。",
    company: "DeepL",
    country: "德国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    price: "€8.74/用户/月",
    version: "",
    date: "2023-01-01",
    link: "https://www.deepl.com/pro/write",
    status: "Active"
  },
  {
    id: "83",
    title: "Mech-Eye LSR XL-GL",
    description: "一款先进的工业3D相机，采用创新的3D技术，能够精确捕捉高反光和深色物体的细节，显著提升工业自动化中的堆垛和分拣效率。",
    company: "Mech-Mind Robotics",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-11-15",
    link: "https://www.mech-mind.com/news/news/002.html",
    status: "Active"
  },
  {
    id: "87",
    title: "Krutrim Pro 多模态模型",
    description: "印度的旗舰级多模态AI模型，支持多种印度语言，具备图像与语音交互功能，应用于云服务与芯片设计等领域。",
    company: "Krutrim AI",
    country: "印度",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    date: "2024-02-15",
    link: "https://olakrutrim.com/",
    status: "Active"
  },
  {
    id: "88",
    title: "OpenHathi-Hi-v0.1",
    description: "一款专注于印地语和其他印度语言的开源大语言模型，旨在推动印度的AI生态系统发展。",
    company: "Sarvam AI",
    country: "印度",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "v0.1",
    date: "2023-12-21",
    link: "https://huggingface.co/sarvamai/OpenHathi-7B-Hi-v0.1-Base",
    status: "Active"
  },
  {
    id: "91",
    title: "Prevent 安全防护系统",
    description: "通过AI预判未知网络攻击并进行自主响应，最新版本将响应速度提升了50%。",
    company: "Darktrace",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2022-07-01",
    link: "https://darktrace.com/platform",
    status: "Active"
  },
  {
    id: "92",
    title: "EXPRESS-1 视频生成模型",
    description: "一个领先的AI视频生成平台，最新模型能生成120种语言的3D虚拟人像，表情动作拟真度达98%。",
    company: "Synthesia",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    price: "$22/月起",
    version: "",
    date: "2024-01-17",
    link: "https://www.synthesia.io/",
    status: "Active"
  },
  {
    id: "93",
    title: "AI 药物靶点发现平台",
    description: "一个用于加速药物发现和开发的端到端AI平台，通过与阿斯利康等药企合作，将罕见病药物的研发周期缩短了50%。",
    company: "BenevolentAI",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2022-01-01",
    link: "https://www.benevolent.com/benevolent-platform",
    status: "Active"
  },
  {
    id: "94",
    title: "企业AI协作平台",
    description: "一个端到端的企业级AI和机器学习平台，支持从数据准备到模型部署的全流程，并集成了AutoML模块以赋能非技术用户。",
    company: "Dataiku",
    country: "法国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2021-08-25",
    link: "https://www.dataiku.com/",
    status: "Active"
  },
  {
    id: "97",
    title: "BioClinical ModernBERT",
    description: "一个专为生物医学领域设计的语言模型，能够理解和处理复杂的临床文本和研究数据，支持药物研发和临床分析。",
    company: "LightOn",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    date: "2023-11-01",
    link: "https://www.lighton.ai/",
    status: "Active"
  },
  {
    id: "98",
    title: "AI搜索引擎SDK",
    description: "一个提供“搜索即服务”的AI平台，支持多模态商品搜索和智能推荐，客户包括LVMH等。",
    company: "Algolia",
    country: "法国",
    category: "Search",
    type: "Service",
    pricing: "商业",
    price: "$0.5/千次请求起",
    version: "",
    date: "2022-01-01",
    link: "https://www.algolia.com/",
    status: "Active"
  },
  {
    id: "100",
    title: "Doosan Cobot 系列",
    description: "斗山机器人推出的协作机器人（Cobot）系列，最新推出的P系列具有更大的负载能力，持续引领工业自动化潮流。",
    company: "Doosan Robotics",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-01-01",
    link: "https://www.doosanrobotics.com/",
    status: "Active"
  },
  {
    id: "101",
    title: "Lunit INSIGHT 影像平台",
    description: "一款AI驱动的医学影像分析平台，能够辅助医生进行癌症筛查，其病理切片分析系统可用于乳腺癌分级预测。",
    company: "Lunit",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2021-01-01",
    link: "https://www.lunit.io/products/lunit-insight-mmg",
    status: "Active"
  },
  {
    id: "102",
    title: "Solar 开源大模型",
    description: "Upstage推出的一款高性能开源语言模型，在Hugging Face开源榜单上韩语任务表现领先，支持长达128K的上下文窗口。",
    company: "Upstage",
    country: "韩国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Pro 2",
    date: "2025-07-10",
    link: "https://huggingface.co/upstage",
    status: "Active"
  },
  {
    id: "105",
    title: "Coveo Relevance AI Platform",
    description: "一个企业级AI搜索和推荐平台，通过个性化体验和生成式AI能力，提升客户服务和电商转化。",
    company: "Coveo",
    country: "加拿大",
    category: "Search",
    type: "Service",
    pricing: "商业",
    date: "2022-01-01",
    link: "https://www.coveo.com/",
    status: "Active"
  },
  {
    id: "106",
    title: "日日新 5.0 (SenseNova)",
    description: "商汤科技发布的最新大模型，支持从文本到3D内容的生成，在多模态理解和创作方面表现卓越。",
    company: "SenseTime",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "5.0",
    date: "2024-04-23",
    link: "https://www.sensetime.com/cn/product-business#llm",
    status: "Active"
  },
  {
    id: "107",
    title: "星火认知大模型 (SparkDesk)",
    description: "科大讯飞推出的认知大模型，具备强大的跨领域知识和语言理解能力，特别在医疗和教育领域进行了深度优化。",
    company: "iFlytek",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "V3.5",
    date: "2024-01-30",
    link: "https://xinghuo.xfyun.cn/",
    status: "Active"
  },
  {
    id: "108",
    title: "百川大模型 (Baichuan)",
    description: "百川智能推出的一系列开源大语言模型，覆盖从7B到530B的多个参数级别，推动了国内大模型开源生态的发展。",
    company: "Baichuan Intelligent Technology",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Baichuan-530B",
    date: "2023-06-15",
    link: "https://github.com/baichuan-inc/Baichuan2",
    status: "Active"
  },
  {
    id: "109",
    title: "DeepSeek-MoE 模型",
    description: "深度求索推出的国内首个开源混合专家（MoE）模型，通过稀疏激活技术在保持高性能的同时降低计算成本。",
    company: "DeepSeek",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "V3.1",
    date: "2025-08-21",
    link: "https://github.com/deepseek-ai",
    status: "Active"
  },
  {
    id: "110",
    title: "豆包大模型 (Doubao)",
    description: "字节跳动推出的通用大模型，覆盖对话、内容创作和多模态应用，最新版本显著提升了性能和效率。",
    company: "ByteDance",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "1.6",
    date: "2023-08-18",
    link: "https://www.doubao.com/",
    status: "Active"
  },
  {
    id: "115",
    title: "GPU Cloud Platform",
    description: "一家专注于为AI和HPC工作负载提供大规模GPU加速的云服务提供商，是OpenAI等公司的核心算力伙伴。",
    company: "CoreWeave",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2022-01-01",
    link: "https://www.coreweave.com/",
    status: "Active"
  },
  {
    id: "116",
    title: "Lattice AI Platform",
    description: "一个用于军事和国防的AI决策平台，能够整合来自传感器的数据并驱动无人系统执行任务，如ALTIUS-700M巡飞弹。",
    company: "Anduril",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-01-01",
    link: "https://www.anduril.com/lattice/",
    status: "Active"
  },
  {
    id: "117",
    title: "Figure 03 人形机器人",
    description: "一款具备语音对话和灵巧操作能力的人形机器人，设计用于在制造业等环境中执行体力劳动任务。",
    company: "Figure AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "03",
    date: "2025-06-07",
    link: "https://www.figure.ai/",
    status: "Active"
  },
  {
    id: "118",
    title: "绿色算力数据中心",
    description: "利用过剩的天然气能源为AI计算提供动力的绿色数据中心，旨在降低AI的碳足迹。",
    company: "Crusoe",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2021-01-01",
    link: "https://crusoe.ai/",
    status: "Active"
  },
  {
    id: "119",
    title: "法律自动化平台",
    description: "一款专为法律专业人士设计的AI平台，能够自动化处理合同分析、法律研究和尽职调查等任务。",
    company: "Harvey",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2022-01-01",
    link: "https://www.harvey.ai/",
    status: "Active"
  },
  {
    id: "121",
    title: "AI 视频编辑工具",
    description: "一个多功能的AI视频创作和编辑平台，提供文本到视频、视频到视频和多种AI魔法工具，用于电影制作和内容创作。",
    company: "Runway",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    price: "Standard: $12/用户/月",
    version: "Gen-4",
    date: "2025-03-31",
    link: "https://runwayml.com/",
    status: "Active"
  },
  {
    id: "123",
    title: "LWM (大型世界模型) 研究项目",
    description: "由斯坦福大学AI实验室（SAIL）领导的研究项目，旨在为自动驾驶构建能够理解和预测世界动态的大型世界模型。",
    company: "Stanford University",
    country: "美国",
    category: "Research",
    type: "Research",
    pricing: "研究",
    date: "2024-05-15",
    link: "https://arxiv.org/abs/2405.09350",
    status: "Active"
  },
  {
    id: "124",
    title: "通用机器人大脑 (Skild Brain)",
    description: "一个旨在为多种机器人硬件提供通用智能的AI平台，使其能够学习和适应不同的任务和环境。",
    company: "Skild AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "Brain",
    date: "2025-07-29",
    link: "https://www.skild.ai/",
    status: "Active"
  },
  {
    id: "125",
    title: "企业AI写作工具Palmyra",
    description: "一个专为企业打造的全栈式生成AI平台，帮助团队创建符合品牌规范和事实准确性的高质量内容。",
    company: "Writer",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2022-01-01",
    link: "https://writer.com/",
    status: "Active"
  },
  {
    id: "127",
    title: "HX-2武装无人机",
    description: "具备抗干扰AI导航系统的武装无人机，为下一代战斗机提供智能决策支持，已部署于实战环境。",
    company: "Helsing",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "HX-2",
    date: "2021-01-01",
    link: "https://helsing.ai/",
    status: "Active"
  },
  {
    id: "128",
    title: "iiQworks 数字化平台",
    description: "整合了仿真规划与远程服务模块的数字化平台，旨在简化工业机器人的编程和部署，降低自动化门槛。",
    company: "KUKA",
    parentCompany: "Midea Group",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2022-01-01",
    link: "https://www.kuka.com/",
    status: "Active"
  },
  {
    id: "129",
    title: "Franka Research 3 (FR3)",
    description: "一款专为科研和高级应用设计的7自由度高精度机械臂，深度集成了NVIDIA Isaac平台，支持复杂的人机交互实验。",
    company: "Franka Robotics",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "FR3",
    date: "2023-01-01",
    link: "https://www.franka.de/",
    status: "Active"
  },
  {
    id: "130",
    title: "Joule AI 助手",
    description: "深度嵌入SAP ERP系统中的AI助手，能够通过自然语言查询财务数据、自动化工作流程，并提供业务洞察。",
    company: "SAP",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-09-01",
    link: "https://www.sap.com/products/artificial-intelligence/joule.html",
    status: "Active"
  },
  {
    id: "131",
    title: "工厂AI质检系统",
    description: "一套基于计算机视觉的自动化质量检测系统，能够高精度识别生产线上的产品缺陷，漏检率极低。",
    company: "Bosch",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-01-01",
    link: "https://www.bosch.com/",
    status: "Active"
  },
  {
    id: "132",
    title: "AI 图像编辑工具",
    description: "一款AI图像编辑工具，支持一键背景替换与高清修复，年收入超5,000万美元。",
    company: "Photoroom",
    country: "法国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    price: "Pro: €9.99/月",
    version: "v5.0",
    date: "2023-01-01",
    link: "https://www.photoroom.com/",
    status: "Active"
  },
  {
    id: "133",
    title: "HyperCLOVA X",
    description: "Naver的旗舰韩语大语言模型，支持多模态输入，并针对韩国本土的法律和文化语境进行了深度优化。",
    company: "Naver",
    country: "韩国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "HyperCLOVA X Think",
    date: "2025-06-30",
    link: "https://www.navercloud.com/product/ai/hyperclovaX",
    status: "Active"
  },
  {
    id: "134",
    title: "Karlo 图像生成模型",
    description: "Kakao Brain推出的文生图模型，支持高质量的图像生成和风格迁移，深度集成于Kakao Talk等社交应用中。",
    company: "Kakao Brain",
    country: "韩国",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "",
    date: "2022-10-18",
    link: "https://www.kakaobrain.com/en/products/karlo",
    status: "Active"
  },
  {
    id: "135",
    title: "Exaone 多模态模型",
    description: "LG AI研究院开发的3000亿参数超大规模多模态模型，能够同时理解和生成文本与图像内容。",
    company: "LG AI Research",
    country: "韩国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "Exaone 4.0",
    date: "2025-07-15",
    link: "https://www.lgresearch.ai/en/exaone",
    status: "Active"
  },
  {
    id: "136",
    title: "Sapeon X330 AI芯片",
    description: "SK Telecom子公司Sapeon推出的新一代AI推理芯片，为数据中心提供高效能、低功耗的AI计算能力。",
    company: "SK Telecom",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "X330",
    date: "2023-11-01",
    link: "https://www.sapeon.com/en",
    status: "Active"
  },
  {
    id: "137",
    title: "ATOM AI训练芯片",
    description: "韩国首款自研的专用于大规模语言模型训练的NPU芯片，旨在打破对外部硬件的依赖。",
    company: "Rebellion",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "ATOM",
    date: "2023-01-01",
    link: "https://rebellions.ai/en/",
    status: "Active"
  },
  {
    id: "138",
    title: "Moloco 机器学习广告平台",
    description: "基于实时机器学习的广告竞价与推荐平台，为移动应用和电商提供高效的程序化广告解决方案。",
    company: "Moloco",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2021-01-01",
    link: "https://www.moloco.com/",
    status: "Active"
  },
  {
    id: "140",
    title: "AI语音克隆技术",
    description: "领先的AI语音生成和克隆技术，能够高保真复刻名人或歌手的声纹，广泛应用于K-pop音乐制作和娱乐产业。",
    company: "Supertone",
    country: "韩国",
    category: "Audio",
    type: "Product",
    pricing: "商业",
    date: "2022-01-01",
    link: "https://supertone.ai/",
    status: "Active"
  },
  {
    id: "141",
    title: "Selvy 语音识别系统",
    description: "一个专为韩语优化的AI语音识别系统，具备高精度的方言识别能力，广泛应用于医疗、金融和客服中心。",
    company: "SELVAS AI",
    country: "韩国",
    category: "Audio",
    type: "Product",
    pricing: "商业",
    date: "2021-01-01",
    link: "https://www.selvasai.com/en/service/aivoice-recognition",
    status: "Active"
  },
  {
    id: "142",
    title: "全渠道客服自动化平台",
    description: "一个全渠道的企业级客服自动化平台，其最新的Agent+智能体支持多语言工单生成和情感分析，大幅提升客户交互效率。",
    company: "Ada",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2022-01-01",
    link: "https://www.ada.cx/",
    status: "Active"
  },
  {
    id: "143",
    title: "AI药物发现平台",
    description: "一个AI驱动的基因组学平台，用于精准预测基因突变的影响并发现新的药物靶点，与辉瑞等制药巨头合作加速罕见病研究。",
    company: "Deep Genomics",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2021-01-01",
    link: "https://www.deepgenomics.com/",
    status: "Active"
  },
  {
    id: "144",
    title: "人形机器人Phoenix",
    description: "一款通用型人形机器人，具备灵巧的机械手操作能力，设计用于在仓储、物流等多种场景中执行复杂任务。",
    company: "Sanctuary AI",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "Phoenix",
    date: "2023-05-16",
    link: "https://www.sanctuary.ai/",
    status: "Active"
  },
  {
    id: "145",
    title: "AI芯片Grayskull",
    description: "由传奇芯片架构师Jim Keller领导，其Grayskull AI芯片以卓越的能效和算力表现，为下一代数据中心和边缘计算提供动力。",
    company: "Tenstorrent",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "Wormhole",
    date: "2025-07-25",
    link: "https://tenstorrent.com/",
    status: "Active"
  },
  {
    id: "146",
    title: "BharatGPT 多模态对话AI平台",
    description: "由CoRover.ai开发，支持12种印度语言和120多种外语交互，深度集成支付网关与ERP系统，获印度政府支持。",
    company: "CoRover.ai",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "Mini",
    date: "2025-06-23",
    link: "https://www.corover.ai/bharatgpt",
    status: "Active"
  },
  {
    id: "149",
    title: "LINGO-2 自动驾驶模型",
    description: "一款创新的自动驾驶模型，能够结合自然语言指令来理解复杂的驾驶场景，显著降低事故率。",
    company: "Wayve",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "研究",
    version: "LINGO-2",
    date: "2025-04-17",
    link: "https://wayve.ai/",
    status: "Active"
  },
  {
    id: "152",
    title: "Matlantis 材料模拟平台",
    description: "一个由AI驱动的原子级材料模拟平台，旨在加速新材料和药物的发现，显著缩短研发周期。",
    company: "Preferred Networks",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-05-01",
    link: "https://matlantis.com/",
    status: "Active"
  },
  {
    id: "153",
    title: "连续思维机 (CTM)",
    description: "基于生物神经时序同步原理的新型AI架构，通过进化算法融合多个小型模型，以应对复杂的决策任务。",
    company: "Sakana AI",
    country: "日本",
    category: "Research",
    type: "Research",
    pricing: "研究",
    date: "2024-03-20",
    link: "https://sakana.ai/",
    status: "Active"
  },
  {
    id: "154",
    title: "MujinController 机器人自动化平台",
    description: "提供一个集成的“无教编程”机器人自动化平台，能够控制工业机器人、AGV和WCS，实现仓库和工厂的全流程自动化。",
    company: "Mujin",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2022-01-01",
    link: "https://www.mujin-corp.com/",
    status: "Active"
  },
  {
    id: "156",
    title: "日语聊天机器人 Rinna",
    description: "源于微软日本团队，是日本最著名的情感对话AI之一，拥有庞大用户基础，并发布了首个本土化的开源语言模型。",
    company: "Rinna",
    country: "日本",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    date: "2022-01-01",
    link: "https://rinna.co.jp/",
    status: "Active"
  },
  {
    id: "157",
    title: "O-beya AI Agent 系统",
    description: "一个多智能体协作系统，通过模拟不同部门（如设计、工程、营销）的AI代理进行协同工作，旨在加速汽车的研发流程。",
    company: "Toyota",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "研究",
    date: "2023-01-01",
    link: "https://global.toyota/",
    status: "Active"
  },
  {
    id: "159",
    title: "Flax Scanner AI-OCR平台",
    description: "一款AI驱动的文档自动化处理平台，利用先进的OCR技术从非结构化文档（如发票、合同）中提取和整理信息。",
    company: "Cinnamon AI",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2021-01-01",
    link: "https://cinnamon.ai/",
    status: "Active"
  },
  {
    id: "161",
    title: "Efficiera AI推理芯片IP",
    description: "一种超低功耗的AI推理加速器IP，专为边缘设备设计，能够以极低的功耗运行复杂的深度学习模型。",
    company: "LeapMind",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-10-01",
    link: "https://leapmind.io/",
    status: "Active"
  },
  {
    id: "162",
    title: "BluStellar 企业AI服务平台",
    description: "一个为企业提供定制化AI解决方案的综合服务平台，旨在加速AI技术在不同行业的导入和应用。",
    company: "NEC",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2024-05-01",
    link: "https://www.nec.com/",
    status: "Active"
  },
  {
    id: "163",
    title: "Serendie 平台",
    description: "一个专注于制造业和可持续发展场景的AI支撑平台，旨在通过数据分析和智能控制优化生产流程和资源利用。",
    company: "Mitsubishi Electric",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2024-05-01",
    link: "https://www.mitsubishielectric.com/",
    status: "Active"
  },
  {
    id: "164",
    title: "Lumada 工业物联网与AI平台",
    description: "日立的核心业务之一，是一个集工业物联网（IoT）、数据分析和AI于一体的综合平台，为各行业提供数字化解决方案。",
    company: "Hitachi",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2024-01-01",
    link: "https://www.hitachi.com/",
    status: "Active"
  },
  {
    id: "165",
    title: "AI语音克隆模型",
    description: "一个行业领先的AI语音生成和克隆平台，能够从短音频片段中生成富有表现力和情感的语音，支持多种语言。",
    company: "ElevenLabs",
    country: "英国",
    category: "Audio",
    type: "Product",
    pricing: "免费增值",
    price: "$5/月起",
    version: "EVI 3",
    date: "2025-07-17",
    link: "https://elevenlabs.io/",
    status: "Active"
  },
  {
    id: "228",
    title: "文心一言 (ERNIE Bot)",
    description: "基于文心大模型系列构建的对话式AI应用，能够与人进行自然语言交互，完成问答、创作、摘要等多种任务，是中国市场领先的生成式AI产品。",
    company: "Baidu",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    price: "Pro: ¥59.9/月",
    version: "ERNIE 5",
    date: "2025-08-21",
    link: "https://yiyan.baidu.com/",
    status: "Active"
  },
  {
    id: "240",
    title: "Cursor AI代码编辑器",
    description: "一款专为AI协作设计的代码编辑器，年收入超1亿美元，估值25亿美元，极大地提升了开发效率。",
    company: "Anysphere",
    country: "美国",
    category: "Developer Tools",
    type: "Product",
    pricing: "商业",
    price: "Pro: $20/月",
    version: "",
    date: "2022-01-01",
    link: "https://cursor.sh/",
    status: "Active"
  },
  {
    id: "241",
    title: "情感智能AI",
    description: "开发自然人机语音交互的AI，专注于情感智能，应用于客服和心理健康领域。",
    company: "Hume AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "EVI 3",
    date: "2025-07-17",
    link: "https://www.hume.ai/",
    status: "Active"
  },
  {
    id: "242",
    title: "Soundful AI音乐生成",
    description: "一个AI驱动的平台，用于生成高质量的免版税音乐，注重伦理和艺术家权益。",
    company: "Soundful",
    country: "美国",
    category: "Audio",
    type: "Product",
    pricing: "免费增值",
    price: "Standard: $9.99/月",
    version: "",
    date: "2021-01-01",
    link: "https://soundful.com/",
    status: "Active"
  },
  {
    id: "244",
    title: "Cerebras 晶圆级AI芯片",
    description: "生产世界上最大的AI芯片（Wafer-Scale Engine），用于加速深度学习训练和推理，已被众多科研机构采用。",
    company: "Cerebras Systems",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "WSE-3",
    date: "2025-02-24",
    link: "https://www.cerebras.net/",
    status: "Active"
  },
  {
    id: "251",
    title: "Forethought AI客服自动化",
    description: "提供生成式AI驱动的客户支持自动化解决方案，帮助大企业解决客户问题，提升服务效率。",
    company: "Forethought",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "Voice",
    date: "2025-03-25",
    link: "https://forethought.ai/",
    status: "Active"
  },
  {
    id: "252",
    title: "Nextera Robotics 工业自动化",
    description: "由麻省理工学院的研究人员创立，专注于开发AI驱动的工业自动化解决方案，获得了Y Combinator的支持。",
    company: "Nextera Robotics",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://www.nexterarobotics.com/",
    status: "Active"
  },
  {
    id: "254",
    title: "Midjourney AI图像生成",
    description: "一个著名的生成式AI平台，能够根据文本提示生成高质量、富有艺术感的图像，在艺术和媒体领域广受欢迎。",
    company: "Midjourney",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    price: "Standard: $30/月",
    version: "Gen-4",
    date: "2025-03-31",
    link: "https://www.midjourney.com/",
    status: "Active"
  },
  {
    id: "255",
    title: "Uizard AI驱动设计平台",
    description: "一个AI驱动的设计平台，帮助非专业人士和团队快速创建网站、移动应用和UI设计的原型，是无代码设计领域的领先者。",
    company: "Uizard",
    country: "美国",
    category: "Platform",
    type: "Product",
    pricing: "免费增值",
    price: "Pro: $12/月",
    version: "Autodesigner 2.0",
    date: "2025-06-12",
    link: "https://uizard.io/",
    status: "Active"
  },
  {
    id: "258",
    title: "DeepNight AI夜视技术",
    description: "一家由Y Combinator支持的初创公司，开发AI驱动的夜视技术，应用于国防和安全领域。",
    company: "DeepNight",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "研究",
    version: "",
    date: "2024-01-01",
    link: "https://www.deepnight.ai/",
    status: "Active"
  },
  {
    id: "259",
    title: "Atla AI错误识别工具",
    description: "一家Y Combinator支持的公司，帮助开发者识别和修复生成式AI模型中的错误，提升模型的可靠性。",
    company: "Atla",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2024-01-01",
    link: "https://www.atla.ai/",
    status: "Active"
  },
  {
    id: "261",
    title: "文心大模型 4.5",
    description: "百度文心大模型的升级版本，在2025年春季发布会推出，进一步提升了模型的综合能力和推理性能。",
    company: "Baidu",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "5",
    date: "2025-08-21",
    link: "https://baike.baidu.com/item/%E6%96%87%E5%BF%83%E4%B8%80%E8%A8%80/62642976",
    status: "Active"
  },
  {
    id: "262",
    title: "通义千问 2.5",
    description: "阿里巴巴通义大模型的迭代版本，在性能和多模态理解方面有显著提升，持续为企业和开发者提供强大的AI能力。",
    company: "Alibaba Cloud",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "2.5",
    date: "2024-05-24",
    link: "https://tongyi.aliyun.com/blog/191573937",
    status: "Active"
  },
  {
    id: "263",
    title: "书生 (INTERN) 2.5",
    description: "商汤科技推出的多模态大模型，专注于理解和生成复杂的视觉和语言内容，是其AI基础设施的核心组成部分。",
    company: "SenseTime",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "研究",
    version: "2.5",
    date: "2023-03-01",
    link: "https://www.sensetime.com/cn/product-business#llm",
    status: "Active"
  },
  {
    id: "264",
    title: "DeepSeek-R1 大模型",
    description: "深度求索推出的大语言模型，因其卓越的性能和开源特性在2025年受到广泛关注，迅速在开发者社区中流行。",
    company: "DeepSeek",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "R1",
    date: "2025-01-10",
    link: "https://github.com/deepseek-ai",
    status: "Active"
  },
  {
    id: "265",
    title: "猫箱 (Cat Box)",
    description: "字节跳动旗下的一款AI聊天和内容创作工具，以其独特的互动体验在年轻用户中广受欢迎。",
    company: "ByteDance",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2025-01-01",
    link: "https://www.doubao.com/",
    status: "Active"
  },
  {
    id: "266",
    title: "即梦AI (JiMeng AI)",
    description: "字节跳动推出的AI图像和视频生成应用，凭借其强大的创作能力和易用性，在2025年实现了惊人的下载量。",
    company: "ByteDance",
    country: "中国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2025-01-01",
    link: "https://www.doubao.com/",
    status: "Active"
  },
  {
    id: "267",
    title: "华为昇腾 (Ascend) AI芯片",
    description: "华为自2016年起全面布局AI，提供包括昇腾（Ascend）系列AI芯片在内的全栈AI解决方案，为各行业提供强大算力支持。",
    company: "Huawei",
    country: "中国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "910D",
    date: "2025-06-24",
    link: "https://www.huawei.com/cn/tech-for-all/intelligent-world/ai",
    status: "Active"
  },
  {
    id: "301",
    title: "Creance AI合规工具",
    description: "与PwC合作开发的AI合规工具，可自动化处理复杂的法规分析和文档生成，提高企业合规效率。",
    company: "Aleph Alpha",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2024-01-01",
    link: "https://aleph-alpha.com/",
    status: "Active"
  },
  {
    id: "302",
    title: "Parloa 对话AI平台",
    description: "一个全渠道的对话式AI平台，用于自动化电话和聊天机器人，旨在提升客户服务的效率和体验。",
    company: "Parloa",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2022-01-01",
    link: "https://parloa.com/",
    status: "Active"
  },
  {
    id: "307",
    title: "Helsing 国防AI平台",
    description: "一个专为国防和国家安全领域构建的AI软件平台，旨在通过实时数据处理和智能分析提升决策速度和准确性。",
    company: "Helsing",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2021-01-01",
    link: "https://helsing.ai/",
    status: "Active"
  },
  {
    id: "311",
    title: "cartagon.ai 决策支持平台",
    description: "一个为企业提供AI驱动的数据分析和决策支持的平台，帮助企业从复杂数据中获取商业洞察。",
    company: "cartagon.ai",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2022-01-01",
    link: "https://cartagon.com/",
    status: "Active"
  },
  {
    id: "314",
    title: "Langdock 语言模型平台",
    description: "一个帮助企业安全、高效地使用大型语言模型的平台，提供数据隐私保护和工作流程集成，提升行政效率。",
    company: "Langdock",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-01-01",
    link: "https://www.langdock.com/",
    status: "Active"
  },
  {
    id: "317",
    title: "PIYA AI 血液测试解读",
    description: "一个利用AI生成多语言血液测试分析报告的服务，帮助用户更好地理解自己的健康数据。",
    company: "PIYA AI",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2024-01-01",
    link: "https://www.piya.ai/",
    status: "Active"
  },
  {
    id: "318",
    title: "PIYA AI 营养补充建议",
    description: "一个基于AI的个性化服务，根据用户的健康数据和目标提供定制化的营养补充建议。",
    company: "PIYA AI",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2025-01-01",
    link: "https://www.piya.ai/",
    status: "Active"
  },
  {
    id: "319",
    title: "Capsula AI 定制解决方案",
    description: "为客户提供世界级的AI项目和产品开发服务，专注于将AI技术应用于实际商业场景。",
    company: "Capsula",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2021-01-01",
    link: "https://capsula.ai/",
    status: "Active"
  },
  {
    id: "320",
    title: "Stardawn AI 企业平台",
    description: "一个为企业提供定制化AI解决方案的平台，旨在通过自动化和数据分析提升运营效率。",
    company: "Stardawn AI",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-01-01",
    link: "https://example.com",
    status: "Active"
  },
  {
    id: "331",
    title: "AIPort 平台",
    description: "为企业提供全面的AI解决方案，旨在通过自动化和数据分析提升运营效率。",
    company: "AIPort",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2021-01-01",
    link: "https://example.com",
    status: "Active"
  },
  {
    id: "344",
    title: "Le Chat 对话AI助手",
    description: "Mistral AI推出的对话式AI助手，支持多语言对话，功能类似ChatGPT，并有移动应用版本。",
    company: "Mistral AI",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    price: "Pro: €20/月",
    version: "",
    date: "2024-02-01",
    link: "https://chat.mistral.ai/",
    status: "Active"
  },
  {
    id: "345",
    title: "Magistral AI模型",
    description: "具备高级推理能力的AI模型系列，其中Magistral Small版本为开源，旨在推动更复杂的AI应用开发。",
    company: "Mistral AI",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Magistral Small",
    date: "2025-06-10",
    link: "https://mistral.ai/",
    status: "Active"
  },
  {
    id: "346",
    title: "代理型AI模型 (Agentic AI)",
    description: "H Company专注于开发代理型AI模型，旨在将用户指令转化为具体行动，提升工作效率和决策能力，旗下产品包括Runner H, Tester H和Surfer H。",
    company: "H Company",
    country: "法国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2025-06-03",
    link: "https://www.h.ai/",
    status: "Active"
  },
  {
    id: "347",
    title: "AI开发助手",
    description: "Poolside致力于简化软件开发流程，其AI开发助手利用生成式AI帮助开发者更高效地编写和调试代码。",
    company: "Poolside",
    country: "法国",
    category: "Developer Tools",
    type: "Product",
    pricing: "商业",
    date: "2025-01-01",
    link: "https://poolside.ai/",
    status: "Active"
  },
  {
    id: "348",
    title: "GenAI模型部署工具",
    description: "Adaptive ML为企业提供高效部署和微调生成式AI模型的工具，旨在降低企业应用AI的技术门槛。",
    company: "Adaptive ML",
    country: "法国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    date: "2025-01-01",
    link: "https://adaptive-ml.com/",
    status: "Active"
  },
  {
    id: "349",
    title: "Mistral Small",
    description: "Mistral AI推出的高效、轻量级的大语言模型，适用于多种需要快速响应和低成本部署的场景。",
    company: "Mistral AI",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "3.1",
    date: "2025-03-17",
    link: "https://mistral.ai/",
    status: "Active"
  },
  {
    id: "350",
    title: "Mistral Medium",
    description: "Mistral AI推出的中等规模的大语言模型，在性能和效率之间取得了良好平衡，适用于更复杂的企业级应用。",
    company: "Mistral AI",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    price: "按需付费",
    version: "3.0",
    date: "2025-05-07",
    link: "https://mistral.ai/",
    status: "Active"
  },
  {
    id: "363",
    title: "无人驾驶卡车AI技术",
    description: "Waabi专注于利用先进AI技术开发无人驾驶卡车，旨在通过更安全、高效的货运方式革新物流和运输行业。",
    company: "Waabi",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2021-01-01",
    link: "https://waabi.ai/",
    status: "Active"
  },
  {
    id: "404",
    title: "完全自动驾驶电动汽车",
    description: "一家致力于开发和生产完全自动驾驶电动汽车（EV）的初创公司，旨在实现L4级以上的自动驾驶能力。",
    company: "Turing Co., Ltd.",
    country: "日本",
    category: "Platform",
    type: "Product",
    pricing: "研究",
    date: "2021-01-01",
    link: "https://www.turing-motors.com/",
    status: "Active"
  },
  {
    id: "406",
    title: "EDGEMATRIX 边缘AI平台",
    description: "一个集成了硬件、软件和云服务的边缘AI平台，用于管理和部署大规模的边缘AI设备和应用。",
    company: "EDGEMATRIX",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2021-01-01",
    link: "https://www.edgematrix.com/",
    status: "Active"
  },
  {
    id: "407",
    title: "fastctl.ai 电商搜索API",
    description: "为电子商务网站提供增强的AI搜索功能，包括语义搜索和聊天机器人，以提升用户购物体验。",
    company: "fastctl.ai",
    country: "日本",
    category: "Search",
    type: "Service",
    pricing: "商业",
    date: "2021-01-01",
    link: "https://fastctl.ai/",
    status: "Active"
  },
  {
    id: "604",
    title: "Synthesia Platform",
    description: "通过文本输入生成带有AI化身和配音的逼真视频，应用于企业培训、营销和客户沟通。",
    company: "Synthesia",
    country: "英国",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    price: "$22/月起",
    version: "",
    date: "2021-01-01",
    link: "https://www.synthesia.io/",
    status: "Active"
  },
  {
    id: "605",
    title: "Bow IPU",
    description: "Graphcore最新一代的智能处理单元（IPU），专为机器学习和大语言模型设计，加速AI计算。",
    company: "Graphcore",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2022-01-01",
    link: "https://www.graphcore.ai/",
    status: "Active"
  },
  {
    id: "610",
    title: "DreamStudio",
    description: "基于Stable Diffusion的商业化平台，用于从文本生成高质量图像。",
    company: "Stability AI",
    country: "英国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    price: "按需付费",
    version: "",
    date: "2022-01-01",
    link: "https://beta.dreamstudio.ai/",
    status: "Active"
  },
  {
    id: "612",
    title: "Oxa MetaDriver",
    description: "Oxa (原Oxbotica) 开发的自动驾驶软件，使用AI优化路径规划和决策。",
    company: "Oxa",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-01-01",
    link: "https://oxa.ai/",
    status: "Active"
  },
  {
    id: "617",
    title: "Fetch.ai Agent Market",
    description: "开发AI代理市场，应用于去中心化金融和智能电网。",
    company: "Fetch.ai",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    date: "2023-01-01",
    link: "https://fetch.ai/",
    status: "Active"
  }
]
