
export interface NewsUpdate {
  id: string;
  date: string;
  company: string;
  logo: string;
  title: string;
  description: string;
  link: string;
  country: '中国' | '美国' | '法国' | '加拿大' | '韩国' | '英国' | '俄罗斯' | '德国' | '印度' | '日本';
  category: '模型' | '应用' | '算力' | '产业' | 'LLM' | 'Image Generation' | 'Audio' | 'Developer Tools' | 'Platform' | 'Search' | 'Research';
  pricing: '免费' | '付费' | '开源' | '免费增值' | '商业' | '研究';
  version?: string;
  parentCompany?: string;
  type?: string;
  imageUrl?: string;
}

const getLogoUrl = (name: string) => {
    const firstChar = name.length > 0 ? name[0].toUpperCase() : 'A';
    return `https://placehold.co/40x40/333333/FFFFFF/png?text=${firstChar}`;
}

export const newsUpdates: NewsUpdate[] = [
  {
    id: "1",
    title: "GPT-4o 多模态模型",
    description: "OpenAI的旗舰多模态模型，可以实时对音频、视觉和文本进行推理，并提供针对性能和延迟优化的Turbo版本。",
    company: "OpenAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "GPT-4o",
    date: "2024-05-13",
    link: "https://openai.com/index/hello-gpt-4o/",
    logo: getLogoUrl("OpenAI"),
  },
  {
    id: "226",
    title: "ChatGPT 对话式AI",
    description: "一个基于GPT系列模型构建的对话式AI，能够以自然、类人的方式与用户互动，广泛用于问答、写作、摘要和创意生成等多种任务。",
    company: "OpenAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "GPT-4o powered",
    date: "2022-11-30",
    link: "https://chat.openai.com/",
    logo: getLogoUrl("OpenAI"),
  },
  {
    id: "200",
    title: "DALL-E 3 图像生成模型",
    description: "OpenAI的旗舰图像生成模型，能够根据文本描述创建高度详细和准确的图像，深度集成于ChatGPT和API中。",
    company: "OpenAI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    version: "DALL-E 3",
    date: "2023-09-20",
    link: "https://openai.com/dall-e-3/",
    logo: getLogoUrl("OpenAI"),
  },
  {
    id: "201",
    title: "Sora 文生视频模型",
    description: "一款能够根据文本指令创建长达一分钟的逼真和富有想象力视频的AI模型，代表了视频生成技术的重大突破。",
    company: "OpenAI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "研究",
    version: "Sora",
    date: "2024-02-15",
    link: "https://openai.com/sora",
    logo: getLogoUrl("OpenAI"),
  },
  {
    id: "202",
    title: "Whisper 语音识别模型",
    description: "一个开源的、鲁棒的语音识别模型，能够将多种语言的语音转录为文本，准确性达到人类水平。",
    company: "OpenAI",
    country: "美国",
    category: "Audio",
    type: "Product",
    pricing: "开源",
    version: "Whisper",
    date: "2022-09-21",
    link: "https://openai.com/research/whisper",
    logo: getLogoUrl("OpenAI"),
  },
  {
    id: "9",
    title: "Mixtral 8x7B 大模型",
    description: "一款高性能的开源稀疏混合专家（SMoE）模型，通过更少的计算资源实现了卓越的性能，在开源社区中广受欢迎。",
    company: "Mistral AI",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Mixtral 8x7B",
    date: "2023-12-09",
    link: "https://mistral.ai/news/mixtral-of-experts/",
    logo: getLogoUrl("Mistral AI"),
  },
  {
    id: "209",
    title: "Mistral Large 模型",
    description: "Mistral AI的旗舰大语言模型，具备顶级的推理能力，支持英语、法语、西班牙语、德语和意大利语，并通过La Plateforme平台提供服务。",
    company: "Mistral AI",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "Mistral Large",
    date: "2024-02-26",
    link: "https://mistral.ai/news/mistral-large/",
    logo: getLogoUrl("Mistral AI"),
  },
  {
    id: "344",
    title: "Le Chat 对话AI助手",
    description: "Mistral AI推出的对话式AI助手，支持多语言对话，功能类似ChatGPT，并有移动应用版本。",
    company: "Mistral AI",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2024-02-01",
    link: "https://chat.mistral.ai/",
    logo: getLogoUrl("Mistral AI"),
  },
  {
    id: "345",
    title: "Magistral AI模型",
    description: "具备高级推理能力的AI模型系列，其中Magistral Small版本为开源，旨在推动更复杂的AI应用开发。",
    company: "Mistral AI",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Magistral Small",
    date: "2025-06-10",
    link: "https://mistral.ai/",
    logo: getLogoUrl("Mistral AI"),
  },
  {
    id: "349",
    title: "Mistral Small",
    description: "Mistral AI推出的高效、轻量级的大语言模型，适用于多种需要快速响应和低成本部署的场景。",
    company: "Mistral AI",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "3.1",
    date: "2025-03-17",
    link: "https://mistral.ai/",
    logo: getLogoUrl("Mistral AI"),
  },
  {
    id: "350",
    title: "Mistral Medium",
    description: "Mistral AI推出的中等规模的大语言模型，在性能和效率之间取得了良好平衡，适用于更复杂的企业级应用。",
    company: "Mistral AI",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "3.0",
    date: "2025-05-07",
    link: "https://mistral.ai/",
    logo: getLogoUrl("Mistral AI"),
  },
  {
    id: "10",
    title: "Embed v3 语义引擎",
    description: "Cohere的最新语义引擎，支持千亿级数据实时检索，显著提升了金融文档等领域的解析效率。",
    company: "Cohere",
    country: "加拿大",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "Embed v3",
    date: "2023-11-01",
    link: "https://cohere.com/models/embed",
    logo: getLogoUrl("Cohere"),
  },
  {
    id: "214",
    title: "Command R+ 大模型",
    description: "Cohere的旗舰级大语言模型，为企业级应用设计，具备强大的多语言能力、检索增强生成（RAG）和工具使用功能。",
    company: "Cohere",
    country: "加拿大",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "Command R+",
    date: "2024-04-04",
    link: "https://cohere.com/blog/command-r-plus",
    logo: getLogoUrl("Cohere"),
  },
  {
    id: "11",
    title: "Hugging Face 开源模型库",
    description: "全球领先的开源AI社区与平台，托管超过50万个模型、数据集和应用，是开发者生态的核心。",
    company: "Hugging Face",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "开源",
    version: "",
    date: "2019-11-01",
    link: "https://huggingface.co/",
    logo: getLogoUrl("Hugging Face"),
  },
  {
    id: "12",
    title: "Perplexity AI 搜索引擎",
    description: "一个由大型语言模型驱动的对话式搜索引擎，提供准确和上下文相关的答案，并支持引用来源。",
    company: "Perplexity",
    country: "美国",
    category: "Search",
    type: "Service",
    pricing: "免费增值",
    version: "",
    date: "2022-08-01",
    link: "https://www.perplexity.ai/",
    logo: getLogoUrl("Perplexity"),
  },
  {
    id: "103",
    title: "QANDA AI解题助手",
    description: "一款面向学生的AI学习应用，通过拍照搜题提供即时解题步骤和知识点讲解，在全球拥有超过8000万用户。",
    company: "QANDA (Mathpresso)",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "免费增值",
    version: "",
    date: "2019-01-01",
    link: "https://qanda.ai/",
    logo: getLogoUrl("QANDA (Mathpresso)"),
  },
  {
    id: "14",
    title: "智谱清言 对话产品",
    description: "面向C端的对话式AI助手，基于GLM大模型构建，提供智能问答和内容创作服务。",
    company: "Zhipu AI",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "智谱清言",
    date: "2023-08-01",
    link: "https://www.zhipuai.cn/",
    logo: getLogoUrl("Zhipu AI"),
  },
  {
    id: "218",
    title: "GLM-4 大模型",
    description: "智谱AI的旗舰级基座大模型，支持128k长上下文，具备多模态能力，并在中文对齐方面表现出色。",
    company: "Zhipu AI",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "GLM-4",
    date: "2024-01-16",
    link: "https://www.zhipuai.cn/glm-4",
    logo: getLogoUrl("Zhipu AI"),
  },
  {
    id: "219",
    title: "CogView 文生图模型",
    description: "智谱AI推出的文生图模型，能够根据文本描述生成高质量的图像，是GLM多模态能力的重要组成部分。",
    company: "Zhipu AI",
    country: "中国",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    version: "CogView 3",
    date: "2024-01-16",
    link: "https://www.zhipuai.cn/gallery",
    logo: getLogoUrl("Zhipu AI"),
  },
  {
    id: "212",
    title: "文心大模型 (ERNIE Foundation Models)",
    description: "百度自主研发的产业级知识增强大模型，涵盖了从自然语言处理到多模态理解的广泛能力，为各行各业提供AI基础能力。",
    company: "Baidu",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "ERNIE 4.0",
    date: "2023-10-17",
    link: "https://wenxin.baidu.com/ebh/index",
    logo: getLogoUrl("Baidu"),
  },
  {
    id: "221",
    title: "文心一格 (ERNIE-ViLG)",
    description: "百度推出的AI艺术和创意辅助平台，能够根据文本描述生成多样风格的图片，支持从风景画到概念艺术的广泛创作。",
    company: "Baidu",
    country: "中国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2022-08-19",
    link: "https://yige.baidu.com/",
    logo: getLogoUrl("Baidu"),
  },
  {
    id: "225",
    title: "Apollo 自动驾驶平台",
    description: "一个开放的自动驾驶平台，为合作伙伴提供一个全面、安全、可靠的一站式解决方案，以创建自己的自动驾驶系统。",
    company: "Baidu",
    country: "中国",
    category: "Platform",
    type: "Service",
    pricing: "开源",
    version: "",
    date: "2017-04-19",
    link: "https://apollo.auto/",
    logo: getLogoUrl("Baidu"),
  },
  {
    id: "228",
    title: "文心一言 (ERNIE Bot)",
    description: "基于文心大模型系列构建的对话式AI应用，能够与人进行自然语言交互，完成问答、创作、摘要等多种任务，是中国市场领先的生成式AI产品。",
    company: "Baidu",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "ERNIE 4.0 powered",
    date: "2023-03-16",
    link: "https://yiyan.baidu.com/",
    logo: getLogoUrl("Baidu"),
  },
  {
    id: "261",
    title: "文心大模型 4.5",
    description: "百度文心大模型的升级版本，在2025年春季发布会推出，进一步提升了模型的综合能力和推理性能。",
    company: "Baidu",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "4.5",
    date: "2025-03-16",
    link: "https://baike.baidu.com/item/%E6%96%87%E5%BF%83%E4%B8%80%E8%A8%80/62642976",
    logo: getLogoUrl("Baidu"),
  },
  {
    id: "16",
    title: "Stable Diffusion 3 图像生成模型",
    description: "Stability AI的旗舰图像生成模型，最新版本支持4K分辨率，在开源社区的调用量已超过10亿次。",
    company: "Stability AI",
    country: "英国",
    category: "Image Generation",
    type: "Product",
    pricing: "开源",
    version: "3.0",
    date: "2024-02-22",
    link: "https://stability.ai/stablediffusion3",
    logo: getLogoUrl("Stability AI"),
  },
  {
    id: "229",
    title: "Stable Audio 2.0",
    description: "Stability AI推出的AI音频生成模型，能够根据文本提示创作高质量、结构完整的完整音轨，时长可达3分钟，并支持音频到音频的转换。",
    company: "Stability AI",
    country: "英国",
    category: "Audio",
    type: "Product",
    pricing: "免费增值",
    version: "2.0",
    date: "2024-04-03",
    link: "https://stability.ai/news/stable-audio-2-0",
    logo: getLogoUrl("Stability AI"),
  },
  {
    id: "17",
    title: "GigaChat MAX 大模型",
    description: "Sberbank的旗舰大语言模型，在俄语任务上对标GPT-4，展示了强大的本地化语言能力。",
    company: "Sberbank",
    country: "俄罗斯",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "MAX",
    date: "2023-11-01",
    link: "https://developers.sber.ru/docs/ru/gigachat/overview",
    logo: getLogoUrl("Sberbank"),
  },
  {
    id: "166",
    title: "YandexGPT 3 大模型",
    description: "Yandex的旗舰级大语言模型，在俄语和多语言任务上表现出色，并推出了针对不同场景优化的Pro、Lite和Summary版本。",
    company: "Yandex",
    country: "俄罗斯",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "3",
    date: "2024-02-15",
    link: "https://cloud.yandex.com/en/services/yandexgpt",
    logo: getLogoUrl("Yandex"),
  },
  {
    id: "321",
    title: "Yandex.Translate",
    description: "一个基于神经网络的机器翻译工具，支持多种语言的高质量翻译。",
    company: "Yandex",
    country: "俄罗斯",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2011-01-01",
    link: "https://translate.yandex.com/",
    logo: getLogoUrl("Yandex"),
  },
  {
    id: "322",
    title: "Yandex.Alice 智能语音助手",
    description: "一款智能语音助手，可用于智能家居设备和Yandex的各种服务中。",
    company: "Yandex",
    country: "俄罗斯",
    category: "Audio",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2017-01-01",
    link: "https://yandex.com/alice",
    logo: getLogoUrl("Yandex"),
  },
  {
    id: "167",
    title: "VK AI 大模型",
    description: "俄罗斯科技巨头VK正在为其庞大的社交和内容生态系统开发自研的大型AI模型。",
    company: "VK",
    country: "俄罗斯",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2024-09-01",
    link: "https://vk.company/en/",
    logo: getLogoUrl("VK"),
  },
  {
    id: "168",
    title: "FindFace Multi 平台",
    description: "一个高精度的多目标面部识别平台，广泛应用于公共安全和商业领域，能够实时识别和分析视频流中的人脸。",
    company: "NtechLab",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "Multi",
    date: "2023-11-01",
    link: "https://ntechlab.com/",
    logo: getLogoUrl("NtechLab"),
  },
  {
    id: "325",
    title: "FindFace 人脸识别系统",
    description: "一套高精度的人脸识别系统，用于公共安全监控和商业客户分析。",
    company: "NtechLab",
    country: "俄罗斯",
    category: "Platform",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2016-01-01",
    link: "https://ntechlab.com/findface-multi/",
    logo: getLogoUrl("NtechLab"),
  },
  {
    id: "169",
    title: "Luna Platform",
    description: "一个全面的计算机视觉和视频分析平台，提供面部识别、物体识别和行为分析等功能，服务于金融、零售和智慧城市等多个行业。",
    company: "VisionLabs",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-10-01",
    link: "https://visionlabs.ai/",
    logo: getLogoUrl("VisionLabs"),
  },
  {
    id: "323",
    title: "LUNA 人脸识别平台",
    description: "一个高性能的人脸识别平台，广泛应用于安防、金融和零售等领域的身份验证。",
    company: "VisionLabs",
    country: "俄罗斯",
    category: "Platform",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2016-01-01",
    link: "https://visionlabs.ai/products/luna-platform",
    logo: getLogoUrl("VisionLabs"),
  },
  {
    id: "324",
    title: "人脸识别 SDK",
    description: "提供一套强大的人脸识别软件开发工具包，方便开发者将先进的面部识别技术集成到自己的应用中。",
    company: "VisionLabs",
    country: "俄罗斯",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2017-01-01",
    link: "https://visionlabs.ai/products/sdk",
    logo: getLogoUrl("VisionLabs"),
  },
  {
    id: "18",
    title: "DBRX 大模型",
    description: "一款拥有 132B 参数的 MoE 架构开源大语言模型，在多项基准测试中表现出色。",
    company: "Databricks",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "DBRX",
    date: "2024-03-27",
    link: "https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm",
    logo: getLogoUrl("Databricks"),
  },
  {
    id: "213",
    title: "Mosaic AI 平台",
    description: "一个统一的平台，用于构建、部署和监控生产级的生成式AI应用，深度集成了数据处理和模型治理能力。",
    company: "Databricks",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-06-28",
    link: "https://www.databricks.com/product/mosaic-ai",
    logo: getLogoUrl("Databricks"),
  },
  {
    id: "20",
    title: "通义万相 视频生成",
    description: "一款先进的AI视频生成模型，能够根据文本或图像输入创造出富有想象力的高清视频内容，其开源版本Wan2.1-VACE推动了社区创新。",
    company: "Alibaba Cloud",
    country: "中国",
    category: "Image Generation",
    type: "Product",
    pricing: "开源",
    version: "Wan2.1-VACE",
    date: "2024-07-10",
    link: "https://tongyi.aliyun.com/wanxiang",
    logo: getLogoUrl("Alibaba Cloud"),
  },
  {
    id: "227",
    title: "通义千问 (Qwen)",
    description: "阿里巴巴达摩院自研的通义大模型，提供强大的通用语言能力，支持多语言、长文本理解，并有多个开源版本（如Qwen1.5）在社区广受欢迎。",
    company: "Alibaba Cloud",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Qwen1.5",
    date: "2023-04-11",
    link: "https://tongyi.aliyun.com/qianwen/",
    logo: getLogoUrl("Alibaba Cloud"),
  },
  {
    id: "262",
    title: "通义千问 2.5",
    description: "阿里巴巴通义大模型的迭代版本，在性能和多模态理解方面有显著提升，持续为企业和开发者提供强大的AI能力。",
    company: "Alibaba Cloud",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "2.5",
    date: "2024-05-24",
    link: "https://tongyi.aliyun.com/blog/191573937",
    logo: getLogoUrl("Alibaba Cloud"),
  },
  {
    id: "21",
    title: "腾讯混元大模型 T1",
    description: "腾讯发布的万亿参数大语言模型，已升级至T1版本，并在2024年推出通用大模型产品“腾讯元宝”，深度融入微信生态。",
    company: "Tencent",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "T1",
    date: "2024-06-01",
    link: "https://hunyuan.tencent.com/",
    logo: getLogoUrl("Tencent"),
  },
  {
    id: "22",
    title: "Kimi 智能助手 (200万字上下文)",
    description: "月之暗面推出的Kimi智能助手，以其突破性的200万字超长无损上下文窗口而闻名，能够高效处理和理解大规模文档。",
    company: "Moonshot AI",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2024-03-18",
    link: "https://kimi.moonshot.cn/",
    logo: getLogoUrl("Moonshot AI"),
  },
  {
    id: "29",
    title: "Claude 3.7 Sonnet",
    description: "Anthropic的下一代中端模型，在性能和成本效益上取得平衡，并引入了动态知识图谱构建等新功能。",
    company: "Anthropic",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "3.7 Sonnet",
    date: "2024-06-20",
    link: "https://www.anthropic.com/product",
    logo: getLogoUrl("Anthropic"),
  },
  {
    id: "210",
    title: "Claude 3 Opus",
    description: "Anthropic的旗舰模型，在高度复杂的任务上提供顶尖性能，为策略、研发和复杂工作流设定了新标准。",
    company: "Anthropic",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "Claude 3 Opus",
    date: "2024-03-04",
    link: "https://www.anthropic.com/news/claude-3-family",
    logo: getLogoUrl("Anthropic"),
  },
  {
    id: "211",
    title: "Claude 3 Haiku",
    description: "Anthropic最快、最紧凑的模型，为需要实时响应的简单查询和任务提供接近即时的响应速度，例如实时聊天和内容审核。",
    company: "Anthropic",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "Claude 3 Haiku",
    date: "2024-03-04",
    link: "https://www.anthropic.com/news/claude-3-family",
    logo: getLogoUrl("Anthropic"),
  },
  {
    id: "32",
    title: "Gemini 1.5 (Flash & Pro)",
    description: "谷歌的下一代旗舰多模态模型，具备百万级Token的超长上下文窗口、多模态推理能力，并提供针对速度和效率优化的Flash版本。",
    company: "Google AI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "1.5",
    date: "2024-05-14",
    link: "https://deepmind.google/technologies/gemini/flash/",
    logo: getLogoUrl("Google AI"),
  },
  {
    id: "36",
    title: "Jules 编码助手",
    description: "一款集成在开发环境中的AI编码助手，旨在帮助开发者更快地编写、调试和优化代码。",
    company: "Google AI",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "免费增值",
    version: "",
    date: "2024-05-14",
    link: "https://deepmind.google/discover/blog/new-models-and-developer-tools-to-build-with-gemini-and-google-ai/",
    logo: getLogoUrl("Google AI"),
  },
  {
    id: "111",
    title: "AlphaFold 3",
    description: "由Google DeepMind与Isomorphic Labs联合发布，能够精准预测蛋白质与包括配体、离子在内的多种分子间的相互作用，加速药物发现。",
    company: "Google AI",
    country: "美国",
    category: "Research",
    type: "Research",
    pricing: "研究",
    version: "3",
    date: "2024-05-08",
    link: "https://deepmind.google/discover/blog/alphafold-3-predicts-the-structure-and-interactions-of-all-of-lifes-molecules/",
    logo: getLogoUrl("Google AI"),
  },
  {
    id: "207",
    title: "Imagen 3 图像生成模型",
    description: "谷歌最先进的文生图模型，能够生成逼真、细节丰富、且深刻理解自然语言提示的图像。",
    company: "Google AI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    version: "Imagen 3",
    date: "2024-05-14",
    link: "https://deepmind.google/technologies/imagen/",
    logo: getLogoUrl("Google AI"),
  },
  {
    id: "215",
    title: "Veo 文生视频模型",
    description: "谷歌最先进的文生视频模型，能够生成长达一分钟以上的高清1080p视频，并能精准理解电影术语，创造出连贯、逼真的视觉效果。",
    company: "Google AI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "研究",
    version: "",
    date: "2024-05-14",
    link: "https://deepmind.google/technologies/veo/",
    logo: getLogoUrl("Google AI"),
  },
  {
    id: "216",
    title: "Project Astra 多模态AI助手",
    description: "谷歌对未来AI助手的愿景，一个实时的、多模态的通用AI智能体，能够通过摄像头和麦克风理解并响应复杂的环境和对话。",
    company: "Google AI",
    country: "美国",
    category: "Research",
    type: "Research",
    pricing: "研究",
    version: "",
    date: "2024-05-14",
    link: "https://deepmind.google/technologies/gemini/project-astra/",
    logo: getLogoUrl("Google AI"),
  },
  {
    id: "217",
    title: "Vertex AI 机器学习平台",
    description: "谷歌云的统一机器学习平台，帮助开发者构建、部署和扩展AI模型，提供了对Gemini等基础模型的访问和工具支持。",
    company: "Google AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://cloud.google.com/vertex-ai",
    logo: getLogoUrl("Google AI"),
  },
  {
    id: "600",
    title: "AlphaGo",
    description: "由Google DeepMind开发的AI围棋程序，2016年击败世界冠军李世乭，是AI发展史上的里程碑。",
    company: "Google AI",
    country: "英国",
    category: "Research",
    type: "Research",
    pricing: "研究",
    version: "",
    date: "2016-03-01",
    link: "https://deepmind.google/discover/blog/alphago-zero-starting-from-scratch/",
    logo: getLogoUrl("Google AI"),
  },
  {
    id: "601",
    title: "AlphaFold",
    description: "由Google DeepMind开发的蛋白质结构预测工具，极大地推动了生物学和医学研究。",
    company: "Google AI",
    country: "英国",
    category: "Research",
    type: "Research",
    pricing: "研究",
    version: "",
    date: "2020-11-01",
    link: "https://www.nature.com/articles/d41586-022-02083-2",
    logo: getLogoUrl("Google AI"),
  },
  {
    id: "602",
    title: "WaveNet",
    description: "由Google DeepMind开发的深度学习模型，用于生成逼真的语音，现广泛应用于谷歌助手。",
    company: "Google AI",
    country: "英国",
    category: "Audio",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2016-09-01",
    link: "https://deepmind.google/discover/blog/wavenet-a-generative-model-for-raw-audio/",
    logo: getLogoUrl("Google AI"),
  },
  {
    id: "38",
    title: "Microsoft 365 Copilot",
    description: "微软的AI助手，已集成到Word、Excel和Teams等Microsoft 365应用中，旨在提高工作场所的生产力和创造力。",
    company: "Microsoft AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-09-26",
    link: "https://www.microsoft.com/en-us/microsoft-365/blog/2023/03/16/introducing-microsoft-365-copilot-your-copilot-for-work/",
    logo: getLogoUrl("Microsoft AI"),
  },
  {
    id: "204",
    title: "Phi-3 小型语言模型 (SLM)",
    description: "微软推出的一系列高性能、低成本的小型语言模型（SLM），专为在资源受限的环境（如移动设备）上高效运行而设计。",
    company: "Microsoft AI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Phi-3",
    date: "2024-04-23",
    link: "https://azure.microsoft.com/en-us/blog/introducing-phi-3-a-highly-capable-and-cost-effective-small-language-model/",
    logo: getLogoUrl("Microsoft AI"),
  },
  {
    id: "205",
    title: "GitHub Copilot 编程助手",
    description: "由GitHub和OpenAI共同开发的AI编程助手，能够实时提供代码建议、补全和生成，深度集成于主流IDE中，极大地提升了开发效率。",
    company: "Microsoft AI",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://github.com/features/copilot",
    logo: getLogoUrl("Microsoft AI"),
  },
  {
    id: "206",
    title: "Microsoft Designer 图像创作工具",
    description: "一款由DALL-E 3驱动的AI图形设计应用，帮助用户通过简单的文本描述快速创建高质量的社交媒体帖子、邀请函、海报和设计。",
    company: "Microsoft AI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2023-04-12",
    link: "https://designer.microsoft.com/",
    logo: getLogoUrl("Microsoft AI"),
  },
  {
    id: "222",
    title: "Microsoft Copilot",
    description: "微软的通用AI助手，深度集成于Windows、Edge浏览器和Bing搜索中，提供对话式应答、内容生成和任务辅助功能。",
    company: "Microsoft AI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2023-11-15",
    link: "https://copilot.microsoft.com/",
    logo: getLogoUrl("Microsoft AI"),
  },
  {
    id: "223",
    title: "Azure AI Platform",
    description: "微软的企业级AI服务平台，提供对OpenAI模型和Phi等自研模型的访问，以及用于构建、部署和管理AI应用的全套工具。",
    company: "Microsoft AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-05-23",
    link: "https://azure.microsoft.com/en-us/solutions/ai",
    logo: getLogoUrl("Microsoft AI"),
  },
  {
    id: "41",
    title: "Blackwell GPU 架构",
    description: "新一代GPU架构，为万亿参数级别的大型语言模型提供实时生成式AI能力，显著提升了计算性能和能效。",
    company: "NVIDIA",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2024-03-18",
    link: "https://nvidianews.nvidia.com/news/nvidia-blackwell-platform-arrives-to-power-a-new-era-of-computing",
    logo: getLogoUrl("NVIDIA"),
  },
  {
    id: "224",
    title: "NVIDIA NIM 推理微服务",
    description: "一套优化的推理微服务，用于大规模部署AI模型，提供预构建的容器和标准API，支持来自NVIDIA、合作伙伴和开源社区的模型。",
    company: "NVIDIA",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2024-03-18",
    link: "https://nvidianews.nvidia.com/news/nvidia-launches-generative-ai-microservices-for-developers-to-create-and-deploy-applications-on-their-platforms",
    logo: getLogoUrl("NVIDIA"),
  },
  {
    id: "44",
    title: "Amazon Bedrock",
    description: "一个用于构建生成式 AI 应用的托管服务，提供来自领先AI公司的多种基础模型选择，包括 Anthropic、Cohere 等。",
    company: "Amazon Web Services",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-09-28",
    link: "https://aws.amazon.com/bedrock/",
    logo: getLogoUrl("Amazon Web Services"),
  },
  {
    id: "208",
    title: "Amazon Q 商业版助手",
    description: "一款为企业打造的生成式AI助手，能够回答问题、生成内容，并根据企业数据和系统采取行动，旨在提高员工生产力。",
    company: "Amazon Web Services",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2024-04-30",
    link: "https://aws.amazon.com/q/",
    logo: getLogoUrl("Amazon Web Services"),
  },
  {
    id: "48",
    title: "Meta AI 助手",
    description: "深度集成于Facebook、Instagram、WhatsApp和Messenger等应用的AI助手，提供对话、内容创作和实时信息服务。",
    company: "Meta AI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2023-09-25",
    link: "https://ai.meta.com/",
    logo: getLogoUrl("Meta AI"),
  },
  {
    id: "203",
    title: "Llama 3 开源大模型",
    description: "Meta推出的下一代开源大语言模型，提供8B和70B两种尺寸，在推理、代码生成和指令遵循方面表现卓越。",
    company: "Meta AI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Llama 3",
    date: "2024-04-18",
    link: "https://ai.meta.com/blog/meta-llama-3/",
    logo: getLogoUrl("Meta AI"),
  },
  {
    id: "220",
    title: "Imagine with Meta AI",
    description: "一个由Meta的Emu模型驱动的独立图像生成工具，允许用户通过文本提示创建高分辨率的图像。",
    company: "Meta AI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2023-12-06",
    link: "https://imagine.meta.com/",
    logo: getLogoUrl("Meta AI"),
  },
  {
    id: "51",
    title: "watsonx 平台",
    description: "一个为企业提供支持的企业级AI和数据平台，用于训练、验证、调整和部署AI模型，包括watsonx.ai、watsonx.data和watsonx.governance。",
    company: "IBM",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-05-09",
    link: "https://www.ibm.com/watsonx",
    logo: getLogoUrl("IBM"),
  },
  {
    id: "56",
    title: "Enterprise Generative AI Platform",
    description: "一个为企业提供支持的平台，用于基础模型的微调、安全保护和部署，确保AI应用的可靠性和可扩展性。",
    company: "Scale AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-12-05",
    link: "https://scale.com/",
    logo: getLogoUrl("Scale AI"),
  },
  {
    id: "61",
    title: "AIP (人工智能平台)",
    description: "一个将大型语言模型（LLM）与企业私有网络集成的平台，专为政府和商业客户设计，支持在安全环境中进行决策和运营。",
    company: "Palantir",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "AIP",
    date: "2023-04-27",
    link: "https://www.palantir.com/platforms/aip/",
    logo: getLogoUrl("Palantir"),
  },
  {
    id: "63",
    title: "Grok-1.5 大模型",
    description: "xAI的旗舰大语言模型，具备长上下文处理能力和先进的推理功能，并能通过X平台实时访问信息。",
    company: "xAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "1.5",
    date: "2024-03-28",
    link: "https://x.ai/blog/grok-1.5",
    logo: getLogoUrl("xAI"),
  },
  {
    id: "230",
    title: "Grok-1.5V 多模态模型",
    description: "Grok-1.5的升级版，增加了处理视觉信息的能力，能够理解图像、文档和图表，在真实世界空间理解基准测试中表现出色。",
    company: "xAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "1.5V",
    date: "2024-04-26",
    link: "https://x.ai/blog/grok-1.5v",
    logo: getLogoUrl("xAI"),
  },
  {
    id: "231",
    title: "Grok-2 图像生成模型",
    description: "Grok模型的最新版本，首次引入了由自研的Aurora模型驱动的图像生成能力，可供X Premium订阅用户使用。",
    company: "xAI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    version: "2",
    date: "2024-08-08",
    link: "https://x.ai/blog/grok-2",
    logo: getLogoUrl("xAI"),
  },
  {
    id: "232",
    title: "PromptIDE 开发环境",
    description: "一个用于提示工程和可解释性研究的集成开发环境，提供SDK和工具来加速复杂提示技术的开发和分析。",
    company: "xAI",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "研究",
    version: "",
    date: "2023-11-08",
    link: "https://x.ai/blog/prompt-ide",
    logo: getLogoUrl("xAI"),
  },
  {
    id: "233",
    title: "Grok 对话式AI",
    description: "xAI推出的首款AI聊天机器人，旨在提供幽默、机智的回答，并以“最大化真相寻求”为目标，设计灵感来源于《银河系漫游指南》。",
    company: "xAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2023-11-04",
    link: "https://grok.x.ai/",
    logo: getLogoUrl("xAI"),
  },
  {
    id: "234",
    title: "Grok-1 开源大模型",
    description: "一个拥有3140亿参数的开源大型语言模型，采用专家混合（MoE）架构，具备强大的语言理解和生成能力。",
    company: "xAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Grok-1",
    date: "2024-03-17",
    link: "https://x.ai/blog/grok-os",
    logo: getLogoUrl("xAI"),
  },
  {
    id: "235",
    title: "Grok-3 大模型",
    description: "被誉为“地表最强 AI”，具备强大的逻辑推理、编码和创意协作能力，支持多种高级功能模式。",
    company: "xAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "3",
    date: "2025-02-01",
    link: "https://x.ai/",
    logo: getLogoUrl("xAI"),
  },
  {
    id: "236",
    title: "Grok-3 Mini 大模型",
    description: "Grok-3的紧凑版本，专注于快速、成本效益高的任务处理，在STEM、数学和编码任务中表现优异。",
    company: "xAI",
    country: "美国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "3 Mini",
    date: "2025-04-01",
    link: "https://x.ai/",
    logo: getLogoUrl("xAI"),
  },
  {
    id: "237",
    title: "Aurora 图像生成模型",
    description: "xAI开发的专有自回归图像生成模型，支持多模态理解、编辑和高品质图像生成，是Grok-2图像生成功能的核心。",
    company: "xAI",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    version: "Aurora",
    date: "2024-08-08",
    link: "https://x.ai/blog/grok-2",
    logo: getLogoUrl("xAI"),
  },
  {
    id: "238",
    title: "Grok Studio",
    description: "一个强大的开发环境，支持代码执行、生成文档、报告及网页游戏，并与Google云端硬盘集成以方便协作。",
    company: "xAI",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2025-04-01",
    link: "https://x.ai/",
    logo: getLogoUrl("xAI"),
  },
  {
    id: "239",
    title: "xAI API",
    description: "允许开发者访问xAI的基础模型，支持多区域低延迟推理、功能调用和自定义系统提示词，并集成了实时网络搜索功能。",
    company: "xAI",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2024-10-01",
    link: "https://x.ai/api",
    logo: getLogoUrl("xAI"),
  },
  {
    id: "78",
    title: "PhariaAI 企业级AI操作系统",
    description: "一个企业级的生成式AI操作系统，支持混合执行、可解释性和合规性，专为政府和企业级应用设计。",
    company: "Aleph Alpha",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://aleph-alpha.com/aleph-alpha-launches-phariaai-the-enterprise-grade-operating-system-for-generative-ai-combining-future-proof-sovereign-design-with-llm-explainability-and-compliance/",
    logo: getLogoUrl("Aleph Alpha"),
  },
  {
    id: "301",
    title: "Creance AI合规工具",
    description: "与PwC合作开发的AI合规工具，可自动化处理复杂的法规分析和文档生成，提高企业合规效率。",
    company: "Aleph Alpha",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2024-01-01",
    link: "https://aleph-alpha.com/",
    logo: getLogoUrl("Aleph Alpha"),
  },
  {
    id: "79",
    title: "DeepL Write Pro",
    description: "一款专为企业用户设计的AI写作助手，提供风格和语气的定制化建议，已扩展支持西班牙语、法语、意大利语和葡萄牙语，持续提升全球商业沟通效率。",
    company: "DeepL",
    country: "德国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://www.deepl.com/pro/write",
    logo: getLogoUrl("DeepL"),
  },
  {
    id: "300",
    title: "DeepL 翻译器",
    description: "基于神经网络的机器翻译工具，支持多种语言的高质量翻译，是全球领先的翻译服务之一。",
    company: "DeepL",
    country: "德国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2017-08-29",
    link: "https://www.deepl.com/translator",
    logo: getLogoUrl("DeepL"),
  },
  {
    id: "83",
    title: "Mech-Eye LSR XL-GL",
    description: "一款先进的工业3D相机，采用创新的3D技术，能够精确捕捉高反光和深色物体的细节，显著提升工业自动化中的堆垛和分拣效率。",
    company: "Mech-Mind Robotics",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-11-15",
    link: "https://www.mech-mind.com/news/news/002.html",
    logo: getLogoUrl("Mech-Mind Robotics"),
  },
  {
    id: "87",
    title: "Krutrim Pro 多模态模型",
    description: "印度的旗舰级多模态AI模型，支持多种印度语言，具备图像与语音交互功能，应用于云服务与芯片设计等领域。",
    company: "Krutrim AI",
    country: "印度",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "Pro",
    date: "2024-02-15",
    link: "https://olakrutrim.com/",
    logo: getLogoUrl("Krutrim AI"),
  },
  {
    id: "88",
    title: "OpenHathi-Hi-v0.1",
    description: "一款专注于印地语和其他印度语言的开源大语言模型，旨在推动印度的AI生态系统发展。",
    company: "Sarvam AI",
    country: "印度",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "v0.1",
    date: "2023-12-21",
    link: "https://sarvam.ai/",
    logo: getLogoUrl("Sarvam AI"),
  },
  {
    id: "89",
    title: "企业级对话机器人平台",
    description: "一个领先的企业级对话AI平台，支持多语言情感分析，广泛应用于亚洲的电商和银行客服领域。",
    company: "Haptik",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2019-01-01",
    link: "https://www.haptik.ai/",
    logo: getLogoUrl("Haptik"),
  },
  {
    id: "91",
    title: "Prevent 安全防护系统",
    description: "通过AI预判未知网络攻击并进行自主响应，最新版本将响应速度提升了50%。",
    company: "Darktrace",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-07-01",
    link: "https://darktrace.com/platform",
    logo: getLogoUrl("Darktrace"),
  },
  {
    id: "613",
    title: "Cyber AI Platform",
    description: "Darktrace开发的AI系统，用于实时检测和响应网络威胁，Antigena是其自主响应模块。",
    company: "Darktrace",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2013-01-01",
    link: "https://darktrace.com/",
    logo: getLogoUrl("Darktrace"),
  },
  {
    id: "92",
    title: "EXPRESS-1 视频生成模型",
    description: "一个领先的AI视频生成平台，最新模型能生成120种语言的3D虚拟人像，表情动作拟真度达98%。",
    company: "Synthesia",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2024-01-17",
    link: "https://www.synthesia.io/",
    logo: getLogoUrl("Synthesia"),
  },
  {
    id: "604",
    title: "Synthesia Platform",
    description: "通过文本输入生成带有AI化身和配音的逼真视频，应用于企业培训、营销和客户沟通。",
    company: "Synthesia",
    country: "英国",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://www.synthesia.io/",
    logo: getLogoUrl("Synthesia"),
  },
  {
    id: "93",
    title: "AI 药物靶点发现平台",
    description: "一个用于加速药物发现和开发的端到端AI平台，通过与阿斯利康等药企合作，将罕见病药物的研发周期缩短了50%。",
    company: "BenevolentAI",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://www.benevolent.com/benevolent-platform",
    logo: getLogoUrl("BenevolentAI"),
  },
  {
    id: "606",
    title: "BenAI Engine",
    description: "BenevolentAI开发的AI驱动药物发现平台，通过数据分析识别潜在药物靶点。",
    company: "BenevolentAI",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "研究",
    version: "",
    date: "2018-01-01",
    link: "https://www.benevolent.com/",
    logo: getLogoUrl("BenevolentAI"),
  },
  {
    id: "94",
    title: "企业AI协作平台",
    description: "一个端到端的企业级AI和机器学习平台，支持从数据准备到模型部署的全流程，并集成了AutoML模块以赋能非技术用户。",
    company: "Dataiku",
    country: "法国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-08-25",
    link: "https://www.dataiku.com/",
    logo: getLogoUrl("Dataiku"),
  },
  {
    id: "95",
    title: "AI保险风控系统",
    description: "一个专为保险行业打造的AI决策平台，通过自动化理赔和反欺诈检测，提升保险公司的运营效率和决策准确性，最新反欺诈引擎识别准确率达98%。",
    company: "Shift Technology",
    country: "法国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://www.shift-technology.com/",
    logo: getLogoUrl("Shift Technology"),
  },
  {
    id: "96",
    title: "AI医学研究平台",
    description: "一个AI驱动的医学研究平台，通过分析患者数据支持药物研发和个性化医疗，与多家大型制药公司合作。",
    company: "OWKIN",
    country: "法国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2016-01-01",
    link: "https://owkin.com/",
    logo: getLogoUrl("OWKIN"),
  },
  {
    id: "97",
    title: "BioClinical ModernBERT",
    description: "一个专为生物医学领域设计的语言模型，能够理解和处理复杂的临床文本和研究数据，支持药物研发和临床分析。",
    company: "LightOn",
    country: "法国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2023-11-01",
    link: "https://www.lighton.ai/",
    logo: getLogoUrl("LightOn"),
  },
  {
    id: "98",
    title: "AI搜索引擎SDK",
    description: "一个提供“搜索即服务”的AI平台，支持多模态商品搜索和智能推荐，客户包括LVMH等。",
    company: "Algolia",
    country: "法国",
    category: "Search",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://www.algolia.com/",
    logo: getLogoUrl("Algolia"),
  },
  {
    id: "99",
    title: "Brightics AI",
    description: "三星SDS推出的企业级数据分析与AI平台，支持数据处理、可视化、机器学习和自然语言理解。",
    company: "Samsung SDS",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2017-01-01",
    link: "https://www.samsungsds.com/",
    logo: getLogoUrl("Samsung SDS"),
  },
  {
    id: "100",
    title: "Doosan Cobot 系列",
    description: "斗山机器人推出的协作机器人（Cobot）系列，最新推出的P系列具有更大的负载能力，持续引领工业自动化潮流。",
    company: "Doosan Robotics",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://www.doosanrobotics.com/",
    logo: getLogoUrl("Doosan Robotics"),
  },
  {
    id: "101",
    title: "Lunit INSIGHT 影像平台",
    description: "一款AI驱动的医学影像分析平台，能够辅助医生进行癌症筛查，其病理切片分析系统可用于乳腺癌分级预测。",
    company: "Lunit",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://www.lunit.io/products/lunit-insight-mmg",
    logo: getLogoUrl("Lunit"),
  },
  {
    id: "102",
    title: "Solar 开源大模型",
    description: "Upstage推出的一款高性能开源语言模型，在Hugging Face开源榜单上韩语任务表现领先，支持长达128K的上下文窗口。",
    company: "Upstage",
    country: "韩国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "",
    date: "2023-12-14",
    link: "https://upstage.ai/solar",
    logo: getLogoUrl("Upstage"),
  },
  {
    id: "104",
    title: "MindBridge Ai Auditor",
    description: "一个AI财务审计平台，通过分析交易数据来识别异常和风险，提升审计效率和准确性。",
    company: "MindBridge AI",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://www.mindbridge.ai/",
    logo: getLogoUrl("MindBridge AI"),
  },
  {
    id: "105",
    title: "Coveo Relevance AI Platform",
    description: "一个企业级AI搜索和推荐平台，通过个性化体验和生成式AI能力，提升客户服务和电商转化。",
    company: "Coveo",
    country: "加拿大",
    category: "Search",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://www.coveo.com/",
    logo: getLogoUrl("Coveo"),
  },
  {
    id: "106",
    title: "日日新 5.0 (SenseNova)",
    description: "商汤科技发布的最新大模型，支持从文本到3D内容的生成，在多模态理解和创作方面表现卓越。",
    company: "SenseTime",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "5.0",
    date: "2024-04-23",
    link: "https://www.sensetime.com/cn/product-business#llm",
    logo: getLogoUrl("SenseTime"),
  },
  {
    id: "263",
    title: "书生 (INTERN) 2.5",
    description: "商汤科技推出的多模态大模型，专注于理解和生成复杂的视觉和语言内容，是其AI基础设施的核心组成部分。",
    company: "SenseTime",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "研究",
    version: "2.5",
    date: "2023-03-01",
    link: "https://www.sensetime.com/cn/product-business#llm",
    logo: getLogoUrl("SenseTime"),
  },
  {
    id: "107",
    title: "星火认知大模型 (SparkDesk)",
    description: "科大讯飞推出的认知大模型，具备强大的跨领域知识和语言理解能力，特别在医疗和教育领域进行了深度优化。",
    company: "iFlytek",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "V3.5",
    date: "2024-01-30",
    link: "https://xinghuo.xfyun.cn/",
    logo: getLogoUrl("iFlytek"),
  },
  {
    id: "108",
    title: "百川大模型 (Baichuan)",
    description: "百川智能推出的一系列开源大语言模型，覆盖从7B到530B的多个参数级别，推动了国内大模型开源生态的发展。",
    company: "Baichuan Intelligent Technology",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "Baichuan-530B",
    date: "2023-06-15",
    link: "https://www.baichuan-ai.com/",
    logo: getLogoUrl("Baichuan Intelligent Technology"),
  },
  {
    id: "109",
    title: "DeepSeek-MoE 模型",
    description: "深度求索推出的国内首个开源混合专家（MoE）模型，通过稀疏激活技术在保持高性能的同时降低计算成本。",
    company: "DeepSeek",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "",
    date: "2024-04-01",
    link: "https://www.deepseek.com/",
    logo: getLogoUrl("DeepSeek"),
  },
  {
    id: "264",
    title: "DeepSeek-R1 大模型",
    description: "深度求索推出的大语言模型，因其卓越的性能和开源特性在2025年受到广泛关注，迅速在开发者社区中流行。",
    company: "DeepSeek",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "开源",
    version: "R1",
    date: "2025-01-10",
    link: "https://www.deepseek.com/",
    logo: getLogoUrl("DeepSeek"),
  },
  {
    id: "110",
    title: "豆包大模型 (Doubao)",
    description: "字节跳动推出的通用大模型，覆盖对话、内容创作和多模态应用，最新版本显著提升了性能和效率。",
    company: "ByteDance",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "1.6",
    date: "2023-08-18",
    link: "https://www.doubao.com/",
    logo: getLogoUrl("ByteDance"),
  },
  {
    id: "265",
    title: "猫箱 (Cat Box)",
    description: "字节跳动旗下的一款AI聊天和内容创作工具，以其独特的互动体验在年轻用户中广受欢迎。",
    company: "ByteDance",
    country: "中国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2025-01-01",
    link: "https://www.doubao.com/",
    logo: getLogoUrl("ByteDance"),
  },
  {
    id: "266",
    title: "即梦AI (JiMeng AI)",
    description: "字节跳动推出的AI图像和视频生成应用，凭借其强大的创作能力和易用性，在2025年实现了惊人的下载量。",
    company: "ByteDance",
    country: "中国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2025-01-01",
    link: "https://www.doubao.com/",
    logo: getLogoUrl("ByteDance"),
  },
  {
    id: "115",
    title: "GPU Cloud Platform",
    description: "一家专注于为AI和HPC工作负载提供大规模GPU加速的云服务提供商，是OpenAI等公司的核心算力伙伴。",
    company: "CoreWeave",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://www.coreweave.com/",
    logo: getLogoUrl("CoreWeave"),
  },
  {
    id: "116",
    title: "Lattice AI Platform",
    description: "一个用于军事和国防的AI决策平台，能够整合来自传感器的数据并驱动无人系统执行任务，如ALTIUS-700M巡飞弹。",
    company: "Anduril",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://www.anduril.com/lattice/",
    logo: getLogoUrl("Anduril"),
  },
  {
    id: "117",
    title: "Figure 02 人形机器人",
    description: "一款具备语音对话和灵巧操作能力的人形机器人，设计用于在制造业等环境中执行体力劳动任务。",
    company: "Figure AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "02",
    date: "2024-03-13",
    link: "https://www.figure.ai/",
    logo: getLogoUrl("Figure AI"),
  },
  {
    id: "118",
    title: "绿色算力数据中心",
    description: "利用过剩的天然气能源为AI计算提供动力的绿色数据中心，旨在降低AI的碳足迹。",
    company: "Crusoe",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://crusoe.ai/",
    logo: getLogoUrl("Crusoe"),
  },
  {
    id: "119",
    title: "法律自动化平台",
    description: "一款专为法律专业人士设计的AI平台，能够自动化处理合同分析、法律研究和尽职调查等任务。",
    company: "Harvey",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://www.harvey.ai/",
    logo: getLogoUrl("Harvey"),
  },
  {
    id: "120",
    title: "AI 医疗笔记工具",
    description: "一个能够实时转录和总结医患对话的AI平台，自动生成结构化的临床笔记，减轻医生的行政负担。",
    company: "Abridge",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://www.abridge.com/",
    logo: getLogoUrl("Abridge"),
  },
  {
    id: "121",
    title: "AI 视频编辑工具",
    description: "一个多功能的AI视频创作和编辑平台，提供文本到视频、视频到视频和多种AI魔法工具，用于电影制作和内容创作。",
    company: "Runway",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2021-01-01",
    link: "https://runwayml.com/",
    logo: getLogoUrl("Runway"),
  },
  {
    id: "123",
    title: "LWM (大型世界模型) 研究项目",
    description: "由斯坦福大学AI实验室（SAIL）领导的研究项目，旨在为自动驾驶构建能够理解和预测世界动态的大型世界模型。",
    company: "Stanford University",
    country: "美国",
    category: "Research",
    type: "Research",
    pricing: "研究",
    version: "",
    date: "2024-05-15",
    link: "https://arxiv.org/abs/2405.09350",
    logo: getLogoUrl("Stanford University"),
  },
  {
    id: "124",
    title: "通用机器人大脑 (Skild Brain)",
    description: "一个旨在为多种机器人硬件提供通用智能的AI平台，使其能够学习和适应不同的任务和环境。",
    company: "Skild AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://www.skild.ai/",
    logo: getLogoUrl("Skild AI"),
  },
  {
    id: "125",
    title: "企业AI写作工具Palmyra",
    description: "一个专为企业打造的全栈式生成AI平台，帮助团队创建符合品牌规范和事实准确性的高质量内容。",
    company: "Writer",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://writer.com/",
    logo: getLogoUrl("Writer"),
  },
  {
    id: "127",
    title: "HX-2武装无人机",
    description: "具备抗干扰AI导航系统的武装无人机，为下一代战斗机提供智能决策支持，已部署于实战环境。",
    company: "Helsing",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "HX-2",
    date: "2021-01-01",
    link: "https://helsing.ai/",
    logo: getLogoUrl("Helsing"),
  },
  {
    id: "307",
    title: "Helsing 国防AI平台",
    description: "一个专为国防和国家安全领域构建的AI软件平台，旨在通过实时数据处理和智能分析提升决策速度和准确性。",
    company: "Helsing",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://helsing.ai/",
    logo: getLogoUrl("Helsing"),
  },
  {
    id: "128",
    title: "iiQworks 数字化平台",
    description: "整合了仿真规划与远程服务模块的数字化平台，旨在简化工业机器人的编程和部署，降低自动化门槛。",
    company: "KUKA",
    parentCompany: "Midea Group",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://www.kuka.com/",
    logo: getLogoUrl("KUKA"),
  },
  {
    id: "129",
    title: "Franka Research 3 (FR3)",
    description: "一款专为科研和高级应用设计的7自由度高精度机械臂，深度集成了NVIDIA Isaac平台，支持复杂的人机交互实验。",
    company: "Franka Robotics",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "FR3",
    date: "2023-01-01",
    link: "https://www.franka.de/",
    logo: getLogoUrl("Franka Robotics"),
  },
  {
    id: "130",
    title: "Joule AI 助手",
    description: "深度嵌入SAP ERP系统中的AI助手，能够通过自然语言查询财务数据、自动化工作流程，并提供业务洞察。",
    company: "SAP",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-09-01",
    link: "https://www.sap.com/products/artificial-intelligence/joule.html",
    logo: getLogoUrl("SAP"),
  },
  {
    id: "131",
    title: "工厂AI质检系统",
    description: "一套基于计算机视觉的自动化质量检测系统，能够高精度识别生产线上的产品缺陷，漏检率极低。",
    company: "Bosch",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://www.bosch.com/",
    logo: getLogoUrl("Bosch"),
  },
  {
    id: "132",
    title: "AI 图像编辑工具",
    description: "一款AI图像编辑工具，支持一键背景替换与高清修复，年收入超5,000万美元。",
    company: "Photoroom",
    country: "法国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    version: "v5.0",
    date: "2023-01-01",
    link: "https://www.photoroom.com/",
    logo: getLogoUrl("Photoroom"),
  },
  {
    id: "133",
    title: "HyperCLOVA X",
    description: "Naver的旗舰韩语大语言模型，支持多模态输入，并针对韩国本土的法律和文化语境进行了深度优化。",
    company: "Naver",
    country: "韩国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "HyperCLOVA X",
    date: "2023-08-24",
    link: "https://www.navercloud.com/product/ai/hyperclovaX",
    logo: getLogoUrl("Naver"),
  },
  {
    id: "351",
    title: "CLOVA AI Platform",
    description: "NAVER的AI平台，提供语音识别、图像识别、自然语言处理等多种功能，为开发者和企业提供强大的AI能力。",
    company: "Naver",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2017-01-01",
    link: "https://clova.ai/",
    logo: getLogoUrl("Naver"),
  },
  {
    id: "352",
    title: "Papago 翻译",
    description: "由NAVER开发的AI翻译应用，利用神经网络技术提供高质量的多语言翻译服务。",
    company: "Naver",
    country: "韩国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2016-01-01",
    link: "https://papago.naver.com/",
    logo: getLogoUrl("Naver"),
  },
  {
    id: "134",
    title: "Karlo 图像生成模型",
    description: "Kakao Brain推出的文生图模型，支持高质量的图像生成和风格迁移，深度集成于Kakao Talk等社交应用中。",
    company: "Kakao Brain",
    country: "韩国",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2022-10-18",
    link: "https://www.kakaobrain.com/en/products/karlo",
    logo: getLogoUrl("Kakao Brain"),
  },
  {
    id: "354",
    title: "Kakao Brain AI研究",
    description: "Kakao的AI研究部门，专注于开发前沿的AI技术，包括超大规模语言模型和图像生成技术。",
    company: "Kakao Brain",
    country: "韩国",
    category: "Research",
    type: "Research",
    pricing: "研究",
    version: "",
    date: "2017-01-01",
    link: "https://www.kakaobrain.com/",
    logo: getLogoUrl("Kakao Brain"),
  },
  {
    id: "353",
    title: "Kakao i 智能助手",
    description: "Kakao的智能语音助手，深度集成于Kakao Talk等应用中，提供信息查询、设备控制等服务。",
    company: "Kakao",
    country: "韩国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2017-01-01",
    link: "https://www.kakao.com/service/Kakaoi",
    logo: getLogoUrl("Kakao"),
  },
  {
    id: "135",
    title: "Exaone 多模态模型",
    description: "LG AI研究院开发的3000亿参数超大规模多模态模型，能够同时理解和生成文本与图像内容。",
    company: "LG AI Research",
    country: "韩国",
    category: "LLM",
    type: "Product",
    pricing: "商业",
    version: "Exaone",
    date: "2022-12-01",
    link: "https://www.lgresearch.ai/en/exaone",
    logo: getLogoUrl("LG AI Research"),
  },
  {
    id: "357",
    title: "LG ThinQ 智能平台",
    description: "LG电子的AI平台，用于智能家居和家电，通过学习用户习惯提供个性化的设备体验和主动服务。",
    company: "LG Electronics",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://www.lg.com/global/thinq",
    logo: getLogoUrl("LG Electronics"),
  },
  {
    id: "136",
    title: "Sapeon X330 AI芯片",
    description: "SK Telecom子公司Sapeon推出的新一代AI推理芯片，为数据中心提供高效能、低功耗的AI计算能力。",
    company: "SK Telecom",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "X330",
    date: "2023-11-01",
    link: "https://www.sapeon.com/en",
    logo: getLogoUrl("SK Telecom"),
  },
  {
    id: "358",
    title: "NUGU 智能音箱",
    description: "SK Telecom的智能语音助手和音箱，提供音乐播放、信息查询、导航等多种服务。",
    company: "SK Telecom",
    country: "韩国",
    category: "Audio",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2016-01-01",
    link: "https://www.nugu.co.kr/",
    logo: getLogoUrl("SK Telecom"),
  },
  {
    id: "359",
    title: "T-Map AI导航",
    description: "韩国领先的AI导航系统，利用实时交通数据和机器学习算法提供最优路线规划。",
    company: "SK Telecom",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "免费增值",
    version: "",
    date: "2017-01-01",
    link: "https://www.tmap.co.kr/",
    logo: getLogoUrl("SK Telecom"),
  },
  {
    id: "137",
    title: "ATOM AI训练芯片",
    description: "韩国首款自研的专用于大规模语言模型训练的NPU芯片，旨在打破对外部硬件的依赖。",
    company: "Rebellion",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "ATOM",
    date: "2023-01-01",
    link: "https://rebellions.ai/en/",
    logo: getLogoUrl("Rebellion"),
  },
  {
    id: "138",
    title: "Moloco 机器学习广告平台",
    description: "基于实时机器学习的广告竞价与推荐平台，为移动应用和电商提供高效的程序化广告解决方案。",
    company: "Moloco",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://www.moloco.com/",
    logo: getLogoUrl("Moloco"),
  },
  {
    id: "139",
    title: "Santa AI教育平台",
    description: "一款AI驱动的个性化学习平台，通过分析学生的学习行为提供定制化的备考路径，已覆盖全球数百万用户。",
    company: "Riiid",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://riiid.co/",
    logo: getLogoUrl("Riiid"),
  },
  {
    id: "140",
    title: "AI语音克隆技术",
    description: "领先的AI语音生成和克隆技术，能够高保真复刻名人或歌手的声纹，广泛应用于K-pop音乐制作和娱乐产业。",
    company: "Supertone",
    country: "韩国",
    category: "Audio",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://supertone.ai/",
    logo: getLogoUrl("Supertone"),
  },
  {
    id: "141",
    title: "Selvy 语音识别系统",
    description: "一个专为韩语优化的AI语音识别系统，具备高精度的方言识别能力，广泛应用于医疗、金融和客服中心。",
    company: "SELVAS AI",
    country: "韩国",
    category: "Audio",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://www.selvasai.com/en/service/aivoice-recognition",
    logo: getLogoUrl("SELVAS AI"),
  },
  {
    id: "142",
    title: "全渠道客服自动化平台",
    description: "一个全渠道的企业级客服自动化平台，其最新的Agent+智能体支持多语言工单生成和情感分析，大幅提升客户交互效率。",
    company: "Ada",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "Agent+",
    date: "2022-01-01",
    link: "https://www.ada.cx/",
    logo: getLogoUrl("Ada"),
  },
  {
    id: "143",
    title: "AI药物发现平台",
    description: "一个AI驱动的基因组学平台，用于精准预测基因突变的影响并发现新的药物靶点，与辉瑞等制药巨头合作加速罕见病研究。",
    company: "Deep Genomics",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://www.deepgenomics.com/",
    logo: getLogoUrl("Deep Genomics"),
  },
  {
    id: "144",
    title: "人形机器人Phoenix",
    description: "一款通用型人形机器人，具备灵巧的机械手操作能力，设计用于在仓储、物流等多种场景中执行复杂任务。",
    company: "Sanctuary AI",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "Phoenix",
    date: "2023-05-16",
    link: "https://www.sanctuary.ai/",
    logo: getLogoUrl("Sanctuary AI"),
  },
  {
    id: "145",
    title: "AI芯片Grayskull",
    description: "由传奇芯片架构师Jim Keller领导，其Grayskull AI芯片以卓越的能效和算力表现，为下一代数据中心和边缘计算提供动力。",
    company: "Tenstorrent",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "Grayskull",
    date: "2022-01-01",
    link: "https://tenstorrent.com/",
    logo: getLogoUrl("Tenstorrent"),
  },
  {
    id: "146",
    title: "BharatGPT 多模态对话AI平台",
    description: "由CoRover.ai开发，支持12种印度语言和120多种外语交互，深度集成支付网关与ERP系统，获印度政府支持。",
    company: "CoRover.ai",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-12-01",
    link: "https://www.corover.ai/bharatgpt",
    logo: getLogoUrl("CoRover.ai"),
  },
  {
    id: "147",
    title: "AI病理分析显微镜",
    description: "一个AI驱动的自动化显微镜，通过深度学习分析血液和尿液样本，能在5分钟内生成初步诊断报告。",
    company: "SigTuple",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://sigtuple.com/",
    logo: getLogoUrl("SigTuple"),
  },
  {
    id: "148",
    title: "Cerebra 工业物联网AI平台",
    description: "一个专为重工业打造的物联网AI平台，通过预测性维护优化石油、能源等行业的设备管理，显著降低运营成本。",
    company: "Flutura",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "v4.0",
    date: "2022-01-01",
    link: "https://www.flutura.com/",
    logo: getLogoUrl("Flutura"),
  },
  {
    id: "149",
    title: "LINGO-1 自动驾驶模型",
    description: "一款创新的自动驾驶模型，能够结合自然语言指令来理解复杂的驾驶场景，显著降低事故率。",
    company: "Wayve",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "研究",
    version: "",
    date: "2024-01-01",
    link: "https://wayve.ai/",
    logo: getLogoUrl("Wayve"),
  },
  {
    id: "603",
    title: "AV2.0 Platform",
    description: "Wayve开发的端到端深度学习自动驾驶系统，使用摄像头和传感器进行环境感知和导航。",
    company: "Wayve",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2019-01-01",
    link: "https://wayve.ai/",
    logo: getLogoUrl("Wayve"),
  },
  {
    id: "151",
    title: "AI 保险定损工具",
    description: "一个专为保险行业设计的AI工具，能够通过分析车辆照片快速评估损伤，将定损速度提升80%。",
    company: "Tractable",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://tractable.ai/",
    logo: getLogoUrl("Tractable"),
  },
  {
    id: "152",
    title: "Matlantis 材料模拟平台",
    description: "一个由AI驱动的原子级材料模拟平台，旨在加速新材料和药物的发现，显著缩短研发周期。",
    company: "Preferred Networks",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-05-01",
    link: "https://matlantis.com/",
    logo: getLogoUrl("Preferred Networks"),
  },
  {
    id: "400",
    title: "PaintsChainer 漫画自动着色工具",
    description: "一个利用深度学习自动为黑白漫画线稿上色的工具，极大地提高了漫画家的创作效率。",
    company: "Preferred Networks",
    country: "日本",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2017-01-01",
    link: "https://paintschainer.preferred.tech/",
    logo: getLogoUrl("Preferred Networks"),
  },
  {
    id: "401",
    title: "Chainer 开源深度学习框架",
    description: "一个强大而灵活的开源深度学习框架，以其“Define-by-Run”方案而闻名，简化了复杂神经网络的构建。",
    company: "Preferred Networks",
    country: "日本",
    category: "Developer Tools",
    type: "Product",
    pricing: "开源",
    version: "",
    date: "2015-01-01",
    link: "https://chainer.org/",
    logo: getLogoUrl("Preferred Networks"),
  },
  {
    id: "153",
    title: "连续思维机 (CTM)",
    description: "基于生物神经时序同步原理的新型AI架构，通过进化算法融合多个小型模型，以应对复杂的决策任务。",
    company: "Sakana AI",
    country: "日本",
    category: "Research",
    type: "Research",
    pricing: "研究",
    version: "",
    date: "2024-03-20",
    link: "https://sakana.ai/",
    logo: getLogoUrl("Sakana AI"),
  },
  {
    id: "154",
    title: "MujinController 机器人自动化平台",
    description: "提供一个集成的“无教编程”机器人自动化平台，能够控制工业机器人、AGV和WCS，实现仓库和工厂的全流程自动化。",
    company: "Mujin",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://www.mujin-corp.com/",
    logo: getLogoUrl("Mujin"),
  },
  {
    id: "155",
    title: "ABEJA Platform零售洞察平台",
    description: "一个面向零售和制造业的AI SaaS平台，提供需求预测、库存优化和客户行为分析等功能，帮助企业实现数字化转型。",
    company: "ABEJA",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://abejainc.com/",
    logo: getLogoUrl("ABEJA"),
  },
  {
    id: "156",
    title: "日语聊天机器人 Rinna",
    description: "源于微软日本团队，是日本最著名的情感对话AI之一，拥有庞大用户基础，并发布了首个本土化的开源语言模型。",
    company: "Rinna",
    country: "日本",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2022-01-01",
    link: "https://rinna.co.jp/",
    logo: getLogoUrl("Rinna"),
  },
  {
    id: "157",
    title: "O-beya AI Agent 系统",
    description: "一个多智能体协作系统，通过模拟不同部门（如设计、工程、营销）的AI代理进行协同工作，旨在加速汽车的研发流程。",
    company: "Toyota",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "研究",
    version: "",
    date: "2023-01-01",
    link: "https://global.toyota/",
    logo: getLogoUrl("Toyota"),
  },
  {
    id: "158",
    title: "Pepper & Whiz 机器人",
    description: "旗下拥有著名的人形交互机器人Pepper和自主清洁机器人Whiz，广泛应用于零售、服务和商业清洁领域。",
    company: "SoftBank Robotics",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://www.softbankrobotics.com/",
    logo: getLogoUrl("SoftBank Robotics"),
  },
  {
    id: "159",
    title: "Flax Scanner AI-OCR平台",
    description: "一款AI驱动的文档自动化处理平台，利用先进的OCR技术从非结构化文档（如发票、合同）中提取和整理信息。",
    company: "Cinnamon AI",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://cinnamon.ai/",
    logo: getLogoUrl("Cinnamon AI"),
  },
  {
    id: "160",
    title: "Autify for Web 测试自动化工具",
    description: "一款面向Web应用测试的AI自动化工具，支持无代码生成和维护测试用例，显著提高软件发布效率。",
    company: "Autify",
    country: "日本",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2019-01-01",
    link: "https://autify.com/",
    logo: getLogoUrl("Autify"),
  },
  {
    id: "161",
    title: "Efficiera AI推理芯片IP",
    description: "一种超低功耗的AI推理加速器IP，专为边缘设备设计，能够以极低的功耗运行复杂的深度学习模型。",
    company: "LeapMind",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-10-01",
    link: "https://leapmind.io/",
    logo: getLogoUrl("LeapMind"),
  },
  {
    id: "162",
    title: "BluStellar 企业AI服务平台",
    description: "一个为企业提供定制化AI解决方案的综合服务平台，旨在加速AI技术在不同行业的导入和应用。",
    company: "NEC",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2024-05-01",
    link: "https://www.nec.com/",
    logo: getLogoUrl("NEC"),
  },
  {
    id: "163",
    title: "Serendie 平台",
    description: "一个专注于制造业和可持续发展场景的AI支撑平台，旨在通过数据分析和智能控制优化生产流程和资源利用。",
    company: "Mitsubishi Electric",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2024-05-01",
    link: "https://www.mitsubishielectric.com/",
    logo: getLogoUrl("Mitsubishi Electric"),
  },
  {
    id: "164",
    title: "Lumada 工业物联网与AI平台",
    description: "日立的核心业务之一，是一个集工业物联网（IoT）、数据分析和AI于一体的综合平台，为各行业提供数字化解决方案。",
    company: "Hitachi",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2024-01-01",
    link: "https://www.hitachi.com/",
    logo: getLogoUrl("Hitachi"),
  },
  {
    id: "165",
    title: "AI语音克隆模型",
    description: "一个行业领先的AI语音生成和克隆平台，能够从短音频片段中生成富有表现力和情感的语音，支持多种语言。",
    company: "ElevenLabs",
    country: "英国",
    category: "Audio",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2023-01-23",
    link: "https://elevenlabs.io/",
    logo: getLogoUrl("ElevenLabs"),
  },
  {
    id: "240",
    title: "Cursor AI代码编辑器",
    description: "一款专为AI协作设计的代码编辑器，年收入超1亿美元，估值25亿美元，极大地提升了开发效率。",
    company: "Anysphere",
    country: "美国",
    category: "Developer Tools",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://cursor.sh/",
    logo: getLogoUrl("Anysphere"),
  },
  {
    id: "241",
    title: "情感智能AI",
    description: "开发自然人机语音交互的AI，专注于情感智能，应用于客服和心理健康领域。",
    company: "Hume AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://hume.ai/",
    logo: getLogoUrl("Hume AI"),
  },
  {
    id: "242",
    title: "Soundful AI音乐生成",
    description: "一个AI驱动的平台，用于生成高质量的免版税音乐，注重伦理和艺术家权益。",
    company: "Soundful",
    country: "美国",
    category: "Audio",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2021-01-01",
    link: "https://soundful.com/",
    logo: getLogoUrl("Soundful"),
  },
  {
    id: "243",
    title: "Groq LPU 推理硬件",
    description: "开发高性能AI推理硬件（LPU），提供极快的语言模型推理速度，其聊天机器人GroqChat展示了其技术实力。",
    company: "Groq",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2016-01-01",
    link: "https://groq.com/",
    logo: getLogoUrl("Groq"),
  },
  {
    id: "244",
    title: "Cerebras 晶圆级AI芯片",
    description: "生产世界上最大的AI芯片（Wafer-Scale Engine），用于加速深度学习训练和推理，已被众多科研机构采用。",
    company: "Cerebras Systems",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2015-01-01",
    link: "https://www.cerebras.net/",
    logo: getLogoUrl("Cerebras Systems"),
  },
  {
    id: "245",
    title: "SambaNova 企业AI平台",
    description: "提供全栈的企业级AI硬件和软件解决方案，其SN40L芯片专为大型语言模型和生成式AI优化。",
    company: "SambaNova Systems",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2017-01-01",
    link: "https://sambanova.ai/",
    logo: getLogoUrl("SambaNova Systems"),
  },
  {
    id: "246",
    title: "H2O.ai 企业AI平台",
    description: "提供开源的H2O平台和自动化的Driverless AI，与戴尔和NVIDIA合作，简化企业AI应用的开发和部署。",
    company: "H2O.ai",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "开源",
    version: "",
    date: "2012-01-01",
    link: "https://h2o.ai/",
    logo: getLogoUrl("H2O.ai"),
  },
  {
    id: "247",
    title: "Instabase AI数据处理",
    description: "利用AI处理非结构化数据，自动化银行业和保险业的复杂工作流程，获得了Andreessen Horowitz等顶级风投的支持。",
    company: "Instabase",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2015-01-01",
    link: "https://instabase.com/",
    logo: getLogoUrl("Instabase"),
  },
  {
    id: "248",
    title: "Tempus 医疗AI",
    description: "一家专注于癌症治疗和个性化医疗的AI公司，利用海量临床和分子数据为医生提供决策支持。",
    company: "Tempus",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2015-01-01",
    link: "https://www.tempus.com/",
    logo: getLogoUrl("Tempus"),
  },
  {
    id: "249",
    title: "Frame AI 客户成功平台",
    description: "一个AI驱动的客户成功平台，能够分析客户反馈和互动数据，为企业提供客户保留和增长的洞察。",
    company: "Frame AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2016-01-01",
    link: "https://frame.ai/",
    logo: getLogoUrl("Frame AI"),
  },
  {
    id: "250",
    title: "Overjet 牙科AI",
    description: "利用计算机视觉和自然语言处理技术，分析牙科X光片和记录，辅助牙医进行诊断和治疗规划。",
    company: "Overjet",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://www.overjet.ai/",
    logo: getLogoUrl("Overjet"),
  },
  {
    id: "251",
    title: "Forethought AI客服自动化",
    description: "提供生成式AI驱动的客户支持自动化解决方案，帮助大企业解决客户问题，提升服务效率。",
    company: "Forethought",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2017-01-01",
    link: "https://forethought.ai/",
    logo: getLogoUrl("Forethought"),
  },
  {
    id: "252",
    title: "Nextera Robotics 工业自动化",
    description: "由麻省理工学院的研究人员创立，专注于开发AI驱动的工业自动化解决方案，获得了Y Combinator的支持。",
    company: "Nextera Robotics",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://www.nexterarobotics.com/",
    logo: getLogoUrl("Nextera Robotics"),
  },
  {
    id: "253",
    title: "Freenome AI癌症早期检测",
    description: "一家致力于通过AI分析血液中的生物信号来进行早期癌症检测的公司，已获得高额融资。",
    company: "Freenome",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "研究",
    version: "",
    date: "2014-01-01",
    link: "https://www.freenome.com/",
    logo: getLogoUrl("Freenome"),
  },
  {
    id: "254",
    title: "Midjourney AI图像生成",
    description: "一个著名的生成式AI平台，能够根据文本提示生成高质量、富有艺术感的图像，在艺术和媒体领域广受欢迎。",
    company: "Midjourney",
    country: "美国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2021-01-01",
    link: "https://www.midjourney.com/",
    logo: getLogoUrl("Midjourney"),
  },
  {
    id: "255",
    title: "Uizard AI驱动设计平台",
    description: "一个AI驱动的设计平台，帮助非专业人士和团队快速创建网站、移动应用和UI设计的原型，是无代码设计领域的领先者。",
    company: "Uizard",
    country: "美国",
    category: "Platform",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2018-01-01",
    link: "https://uizard.io/",
    logo: getLogoUrl("Uizard"),
  },
  {
    id: "256",
    title: "Vectra AI 网络威胁检测",
    description: "利用AI实时检测混合云环境中的网络威胁和攻击，与AWS和Azure等云服务商紧密合作。",
    company: "Vectra AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2011-01-01",
    link: "https://www.vectra.ai/",
    logo: getLogoUrl("Vectra AI"),
  },
  {
    id: "257",
    title: "MOSTLY AI 合成数据生成",
    description: "一个生成式AI平台，能够创建符合隐私法规的合成数据，用于AI模型的训练和测试，解决了数据隐私的挑战。",
    company: "MOSTLY AI",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2017-01-01",
    link: "https://mostly.ai/",
    logo: getLogoUrl("MOSTLY AI"),
  },
  {
    id: "258",
    title: "DeepNight AI夜视技术",
    description: "一家由Y Combinator支持的初创公司，开发AI驱动的夜视技术，应用于国防和安全领域。",
    company: "DeepNight",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "研究",
    version: "",
    date: "2024-01-01",
    link: "https://www.deepnight.ai/",
    logo: getLogoUrl("DeepNight"),
  },
  {
    id: "259",
    title: "Atla AI错误识别工具",
    description: "一家Y Combinator支持的公司，帮助开发者识别和修复生成式AI模型中的错误，提升模型的可靠性。",
    company: "Atla",
    country: "美国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2024-01-01",
    link: "https://www.atla.ai/",
    logo: getLogoUrl("Atla"),
  },
  {
    id: "260",
    title: "Insitro AI药物发现平台",
    description: "由斯坦福教授Daphne Koller创立，利用AI和机器学习技术优化药物发现和开发流程，与Gilead Sciences等大型药企合作。",
    company: "Insitro",
    country: "美国",
    category: "Platform",
    type: "Service",
    pricing: "研究",
    version: "",
    date: "2018-01-01",
    link: "https://insitro.com/",
    logo: getLogoUrl("Insitro"),
  },
  {
    id: "267",
    title: "华为昇腾 (Ascend) AI芯片",
    description: "华为自2016年起全面布局AI，提供包括昇腾（Ascend）系列AI芯片在内的全栈AI解决方案，为各行业提供强大算力支持。",
    company: "Huawei",
    country: "中国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-10-10",
    link: "https://www.huawei.com/cn/tech-for-all/intelligent-world/ai",
    logo: getLogoUrl("Huawei"),
  },
  {
    id: "268",
    title: "旷视Brain++ 平台",
    description: "旷视科技是一家全球领先的人工智能公司，其Brain++ AI生产力平台和FaceID人脸识别技术广泛应用于金融、安防和零售等领域。",
    company: "Megvii",
    country: "中国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2014-01-01",
    link: "https://www.megvii.com/",
    logo: getLogoUrl("Megvii"),
  },
  {
    id: "269",
    title: "依图“求索”系列AI芯片",
    description: "依图科技专注于计算机视觉和AI芯片技术，其自研的“求索”系列芯片为城市安防、智慧金融和智能医疗等领域提供高性能算力。",
    company: "Yitu Technology",
    country: "中国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "求索QuestCore",
    date: "2019-05-09",
    link: "https://www.yitutech.com/",
    logo: getLogoUrl("Yitu Technology"),
  },
  {
    id: "302",
    title: "Parloa 对话AI平台",
    description: "一个全渠道的对话式AI平台，用于自动化电话和聊天机器人，旨在提升客户服务的效率和体验。",
    company: "Parloa",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://parloa.com/",
    logo: getLogoUrl("Parloa"),
  },
  {
    id: "303",
    title: "N8n 工作流自动化",
    description: "一款可扩展的工作流自动化工具，支持通过可视化界面连接不同的应用程序和API，并集成了AI增强功能。",
    company: "N8n",
    country: "德国",
    category: "Developer Tools",
    type: "Service",
    pricing: "开源",
    version: "",
    date: "2019-01-01",
    link: "https://n8n.io/",
    logo: getLogoUrl("N8n"),
  },
  {
    id: "304",
    title: "HIRO 自动化平台",
    description: "Arago公司的旗舰AI平台，专注于IT和业务流程的自动化，帮助企业提高运营效率。",
    company: "Arago",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2015-01-01",
    link: "https://arago.co/",
    logo: getLogoUrl("Arago"),
  },
  {
    id: "305",
    title: "Acrolinx 内容治理平台",
    description: "一个AI驱动的内容治理平台，帮助企业创建符合品牌、风格和合规要求的高质量内容。",
    company: "Acrolinx",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2010-01-01",
    link: "https://www.acrolinx.com/",
    logo: getLogoUrl("Acrolinx"),
  },
  {
    id: "306",
    title: "omni:us 文档提取平台",
    description: "一个专为保险行业设计的AI平台，能够从高度可变的文档（如理赔申请）中自动提取和处理结构化数据。",
    company: "omni:us",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://omnius.com/",
    logo: getLogoUrl("omni:us"),
  },
  {
    id: "308",
    title: "Volocopter AI 飞行系统",
    description: "为旗下的电动垂直起降（eVTOL）空中出租车和货运无人机提供AI驱动的自主飞行和运营支持系统。",
    company: "Volocopter",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2019-01-01",
    link: "https://www.volocopter.com/",
    logo: getLogoUrl("Volocopter"),
  },
  {
    id: "309",
    title: "CoachHub 人才发展平台",
    description: "一个全球领先的数字化辅导平台，利用AI为企业员工提供个性化的职业发展和领导力培训解决方案。",
    company: "CoachHub",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://www.coachhub.com/",
    logo: getLogoUrl("CoachHub"),
  },
  {
    id: "310",
    title: "Quantum-Systems AI 无人机",
    description: "为旗下的电动垂直起降（eVTOL）无人机提供先进的AI功能，包括自主飞行、数据采集和实时分析。",
    company: "Quantum-Systems",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://www.quantum-systems.com/",
    logo: getLogoUrl("Quantum-Systems"),
  },
  {
    id: "311",
    title: "cartagon.ai 决策支持平台",
    description: "一个为企业提供AI驱动的数据分析和决策支持的平台，帮助企业从复杂数据中获取商业洞察。",
    company: "cartagon.ai",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://cartagon.com/",
    logo: getLogoUrl("cartagon.ai"),
  },
  {
    id: "312",
    title: "tado° 智能恒温器",
    description: "一款智能家居产品，利用AI算法学习用户习惯和天气数据，自动优化家庭供暖和制冷，以节省能源。",
    company: "tado°",
    country: "德国",
    category: "Platform",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://www.tado.com/",
    logo: getLogoUrl("tado°"),
  },
  {
    id: "313",
    title: "KONUX 铁路监控平台",
    description: "一个结合了物联网传感器和AI的预测性维护平台，用于监控铁路基础设施（如道岔）的健康状况，预防故障。",
    company: "KONUX",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2014-01-01",
    link: "https://www.konux.com/",
    logo: getLogoUrl("KONUX"),
  },
  {
    id: "314",
    title: "Langdock 语言模型平台",
    description: "一个帮助企业安全、高效地使用大型语言模型的平台，提供数据隐私保护和工作流程集成，提升行政效率。",
    company: "Langdock",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://www.langdock.com/",
    logo: getLogoUrl("Langdock"),
  },
  {
    id: "315",
    title: "Nect 自拍身份验证",
    description: "一个基于AI的自动化身份验证系统，用户通过自拍视频即可完成身份核验，广泛应用于金融和保险行业。",
    company: "Nect",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2019-01-01",
    link: "https://nect.com/",
    logo: getLogoUrl("Nect"),
  },
  {
    id: "316",
    title: "Ada 个人健康助手",
    description: "一款全球流行的AI健康应用，通过对话界面帮助用户了解自身症状，并提供可靠的医疗信息和建议。",
    company: "Ada Health",
    country: "德国",
    category: "Platform",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2016-01-01",
    link: "https://ada.com/",
    logo: getLogoUrl("Ada Health"),
  },
  {
    id: "317",
    title: "PIYA AI 血液测试解读",
    description: "一个利用AI生成多语言血液测试分析报告的服务，帮助用户更好地理解自己的健康数据。",
    company: "PIYA AI",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2024-01-01",
    link: "https://www.piya.ai/",
    logo: getLogoUrl("PIYA AI"),
  },
  {
    id: "318",
    title: "PIYA AI 营养补充建议",
    description: "一个基于AI的个性化服务，根据用户的健康数据和目标提供定制化的营养补充建议。",
    company: "PIYA AI",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2025-01-01",
    link: "https://www.piya.ai/",
    logo: getLogoUrl("PIYA AI"),
  },
  {
    id: "319",
    title: "Capsula AI 定制解决方案",
    description: "为客户提供世界级的AI项目和产品开发服务，专注于将AI技术应用于实际商业场景。",
    company: "Capsula",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://capsula.ai/",
    logo: getLogoUrl("Capsula"),
  },
  {
    id: "320",
    title: "Stardawn AI 企业平台",
    description: "一个为企业提供定制化AI解决方案的平台，旨在通过自动化和数据分析提升运营效率。",
    company: "Stardawn AI",
    country: "德国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://example.com",
    logo: getLogoUrl("Stardawn AI"),
  },
  {
    id: "326",
    title: "SberAI 平台",
    description: "Sberbank的综合AI平台，提供包括语音识别、图像识别在内的多种服务，支持企业级AI应用开发。",
    company: "Sberbank",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://www.sberbank.com/ai",
    logo: getLogoUrl("Sberbank"),
  },
  {
    id: "327",
    title: "Cognitive Agro Pilot",
    description: "一款专为农业机械（如联合收割机、拖拉机）设计的自动驾驶系统，旨在提高农业生产效率。",
    company: "Cognitive Pilot",
    country: "俄罗斯",
    category: "Platform",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2019-01-01",
    link: "https://cognitivepilot.com/",
    logo: getLogoUrl("Cognitive Pilot"),
  },
  {
    id: "328",
    title: "FineReader",
    description: "一款行业领先的光学字符识别（OCR）软件，能够将扫描的文档、PDF和图像转换为可编辑、可搜索的格式。",
    company: "Abbyy",
    country: "俄罗斯",
    category: "Developer Tools",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "1993-01-01",
    link: "https://pdf.abbyy.com/finereader-pdf/",
    logo: getLogoUrl("Abbyy"),
  },
  {
    id: "329",
    title: "Comprehend",
    description: "一个智能文档处理（IDP）平台，利用自然语言处理（NLP）技术理解和提取非结构化文档中的数据。",
    company: "Abbyy",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://www.abbyy.com/vantage/",
    logo: getLogoUrl("Abbyy"),
  },
  {
    id: "330",
    title: "Prisma 图像处理应用",
    description: "一款流行的移动应用，使用神经网络和AI技术将用户的照片转化为模仿著名艺术家风格的艺术作品。",
    company: "Prisma Labs",
    country: "俄罗斯",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2016-01-01",
    link: "https://prisma-ai.com/",
    logo: getLogoUrl("Prisma Labs"),
  },
  {
    id: "331",
    title: "AIPort 平台",
    description: "为企业提供全面的AI解决方案，旨在通过自动化和数据分析提升运营效率。",
    company: "AIPort",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://example.com",
    logo: getLogoUrl("AIPort"),
  },
  {
    id: "332",
    title: "Data Monsters 平台",
    description: "一家AI咨询和服务公司，提供从数据分析到机器学习模型部署的端到端解决方案。",
    company: "Data Monsters",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://datamonsters.co/",
    logo: getLogoUrl("Data Monsters"),
  },
  {
    id: "333",
    title: "情感识别技术",
    description: "开发用于识别和分析人类情感的AI技术，应用于市场研究、用户体验分析和心理健康领域。",
    company: "Neurodata Lab",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2017-01-01",
    link: "https://neurodatalab.com/",
    logo: getLogoUrl("Neurodata Lab"),
  },
  {
    id: "334",
    title: "Botkin.AI 医疗影像分析平台",
    description: "一个利用AI分析CT、X光等医疗影像的平台，辅助医生进行肺癌等疾病的早期诊断。",
    company: "Botkin.AI",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2019-01-01",
    link: "https://botkin.ai/en/",
    logo: getLogoUrl("Botkin.AI"),
  },
  {
    id: "335",
    title: "Intento 机器翻译API",
    description: "一个AI集成平台，允许开发者通过单一API访问和评估多种机器翻译和语言模型引擎。",
    company: "Intento",
    country: "俄罗斯",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2017-01-01",
    link: "https://intento.ai/",
    logo: getLogoUrl("Intento"),
  },
  {
    id: "336",
    title: "Neurotrend 神经科学研究平台",
    description: "一家神经营销公司，使用AI分析脑电图（EEG）和眼动追踪数据，以评估消费者对广告和产品的反应。",
    company: "Neurotrend",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://neuro-trend.ru/",
    logo: getLogoUrl("Neurotrend"),
  },
  {
    id: "337",
    title: "Smart IDReader",
    description: "利用AI技术自动识别和提取身份证、护照、驾照等各类文档中的信息，支持移动端和服务器端部署。",
    company: "Smart Engines",
    country: "俄罗斯",
    category: "Developer Tools",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2015-01-01",
    link: "https://smartengines.com/",
    logo: getLogoUrl("Smart Engines"),
  },
  {
    id: "338",
    title: "RoboCV X-MOTION NG",
    description: "为仓库和物流中心提供自动驾驶系统，用于叉车和拖车等设备的自动化改造。",
    company: "RoboCV",
    country: "俄罗斯",
    category: "Platform",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2016-01-01",
    link: "https://robocv.ru/en/",
    logo: getLogoUrl("RoboCV"),
  },
  {
    id: "339",
    title: "Geosplit 平台",
    description: "为石油和天然气行业提供创新的油藏监测技术，使用AI分析标记物数据来优化油井生产。",
    company: "Geosplit",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2017-01-01",
    link: "https://geosplit.ru/en/",
    logo: getLogoUrl("Geosplit"),
  },
  {
    id: "340",
    title: "Eywa Kitchen AI",
    description: "一个智能厨房解决方案，旨在利用AI技术优化家庭和商业厨房的烹饪过程。",
    company: "Eywa Kitchen",
    country: "俄罗斯",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2019-01-01",
    link: "https://example.com",
    logo: getLogoUrl("Eywa Kitchen"),
  },
  {
    id: "341",
    title: "KVINT AI",
    description: "一家AI电话运营商，使用AI语音机器人为企业提供客户服务和呼叫中心自动化解决方案。",
    company: "KVINT",
    country: "俄罗斯",
    category: "Audio",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://example.com",
    logo: getLogoUrl("KVINT"),
  },
  {
    id: "342",
    title: "OhMyBet! AI",
    description: "一款体育博彩预测工具，利用AI算法分析历史数据和比赛统计数据来预测比赛结果。",
    company: "OhMyBet!",
    country: "俄罗斯",
    category: "Platform",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2019-01-01",
    link: "https://example.com",
    logo: getLogoUrl("OhMyBet!"),
  },
  {
    id: "343",
    title: "Vocord FaceControl",
    description: "一个多功能的生物识别平台，提供高精度的人脸识别系统，用于安全监控和访问控制。",
    company: "Vocord",
    country: "俄罗斯",
    category: "Platform",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2014-01-01",
    link: "https://vocord.com/",
    logo: getLogoUrl("Vocord"),
  },
  {
    id: "346",
    title: "代理型AI模型 (Agentic AI)",
    description: "H Company专注于开发代理型AI模型，旨在将用户指令转化为具体行动，提升工作效率和决策能力，旗下产品包括Runner H, Tester H和Surfer H。",
    company: "H Company",
    country: "法国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2025-06-03",
    link: "https://www.h.ai/",
    logo: getLogoUrl("H Company"),
  },
  {
    id: "347",
    title: "AI开发助手",
    description: "Poolside致力于简化软件开发流程，其AI开发助手利用生成式AI帮助开发者更高效地编写和调试代码。",
    company: "Poolside",
    country: "法国",
    category: "Developer Tools",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2025-01-01",
    link: "https://poolside.ai/",
    logo: getLogoUrl("Poolside"),
  },
  {
    id: "348",
    title: "GenAI模型部署工具",
    description: "Adaptive ML为企业提供高效部署和微调生成式AI模型的工具，旨在降低企业应用AI的技术门槛。",
    company: "Adaptive ML",
    country: "法国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2025-01-01",
    link: "https://adaptive-ml.com/",
    logo: getLogoUrl("Adaptive ML"),
  },
  {
    id: "355",
    title: "Bixby 语音助手",
    description: "三星电子的旗舰智能语音助手，内置于Galaxy智能手机、电视和家电中，提供设备控制和信息服务。",
    company: "Samsung Electronics",
    country: "韩国",
    category: "LLM",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2017-01-01",
    link: "https://www.samsung.com/global/galaxy/apps/bixby/",
    logo: getLogoUrl("Samsung Electronics"),
  },
  {
    id: "356",
    title: "SmartThings 智能家居",
    description: "三星的智能家居平台，利用AI技术优化和自动化互联设备的管理，提升家庭生活的便利性。",
    company: "Samsung Electronics",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2014-01-01",
    link: "https://www.smartthings.com/",
    logo: getLogoUrl("Samsung Electronics"),
  },
  {
    id: "360",
    title: "GiGA Genie 智能音箱",
    description: "KT Corporation的智能语音助手和家庭媒体中心，集成电视、音乐和物联网设备控制功能。",
    company: "KT Corporation",
    country: "韩国",
    category: "Audio",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2017-01-01",
    link: "https://gigagenie.kt.com/",
    logo: getLogoUrl("KT Corporation"),
  },
  {
    id: "361",
    title: "Hancom AI 平台",
    description: "提供文档分析、语音识别等企业级AI服务，旨在提高办公效率和自动化水平。",
    company: "Hancom",
    country: "韩国",
    category: "Developer Tools",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2019-01-01",
    link: "https://www.hancom.com/en/product/ai.jsp",
    logo: getLogoUrl("Hancom"),
  },
  {
    id: "362",
    title: "Saltlux AI 平台",
    description: "提供基于自然语言处理和知识图谱的企业级AI解决方案，包括智能客服和数据分析。",
    company: "Saltlux",
    country: "韩国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2015-01-01",
    link: "https://www.saltlux.com/",
    logo: getLogoUrl("Saltlux"),
  },
  {
    id: "363",
    title: "无人驾驶卡车AI技术",
    description: "Waabi专注于利用先进AI技术开发无人驾驶卡车，旨在通过更安全、高效的货运方式革新物流和运输行业。",
    company: "Waabi",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://waabi.ai/",
    logo: getLogoUrl("Waabi"),
  },
  {
    id: "364",
    title: "机器人仓储服务",
    description: "Attabotics提供机器人仓储服务，利用AI优化仓库运营和履行流程，改变了仓储和物流行业。",
    company: "Attabotics",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2019-01-01",
    link: "https://www.attabotics.com/",
    logo: getLogoUrl("Attabotics"),
  },
  {
    id: "365",
    title: "AI驱动的视频安全与商业分析平台",
    description: "Solink提供AI驱动的威胁识别系统，用于视频安全和商业分析，广泛应用于零售和酒店行业。",
    company: "Solink",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://solink.com/",
    logo: getLogoUrl("Solink"),
  },
  {
    id: "366",
    title: "自主建筑节能技术",
    description: "BrainBox AI提供自主建筑技术，利用AI优化商业建筑的能耗并减少碳足迹，促进行业可持续发展。",
    company: "BrainBox AI",
    country: "加拿大",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2019-01-01",
    link: "https://www.brainboxai.com/",
    logo: getLogoUrl("BrainBox AI"),
  },
  {
    id: "402",
    title: "MAGELLAN BLOCKS 机器学习平台",
    description: "一个云端机器学习平台，通过拖放式界面简化了从数据分析到模型部署的全过程，无需编码。",
    company: "Groovenauts",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2016-01-01",
    link: "https://www.groovenauts.jp/magellan-blocks/",
    logo: getLogoUrl("Groovenauts"),
  },
  {
    id: "403",
    title: "Smart Brain Doc AI医疗诊断",
    description: "提供基于AI的MRI影像分析服务，专注于脑部疾病的早期筛查和预防，帮助用户管理健康风险。",
    company: "SmartScan",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://smartscan.co.jp/",
    logo: getLogoUrl("SmartScan"),
  },
  {
    id: "404",
    title: "完全自动驾驶电动汽车",
    description: "一家致力于开发和生产完全自动驾驶电动汽车（EV）的初创公司，旨在实现L4级以上的自动驾驶能力。",
    company: "Turing Co., Ltd.",
    country: "日本",
    category: "Platform",
    type: "Product",
    pricing: "研究",
    version: "",
    date: "2020-01-01",
    link: "https://www.turing-motors.com/",
    logo: getLogoUrl("Turing Co., Ltd."),
  },
  {
    id: "405",
    title: "Xpression 图形生成平台",
    description: "一个AI驱动的计算机图形生成平台，专注于创造逼真的虚拟形象和动态图形内容。",
    company: "Xpression",
    country: "日本",
    category: "Image Generation",
    type: "Product",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://xpression.jp/",
    logo: getLogoUrl("Xpression"),
  },
  {
    id: "406",
    title: "EDGEMATRIX 边缘AI平台",
    description: "一个集成了硬件、软件和云服务的边缘AI平台，用于管理和部署大规模的边缘AI设备和应用。",
    company: "EDGEMATRIX",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://www.edgematrix.com/",
    logo: getLogoUrl("EDGEMATRIX"),
  },
  {
    id: "407",
    title: "fastctl.ai 电商搜索API",
    description: "为电子商务网站提供增强的AI搜索功能，包括语义搜索和聊天机器人，以提升用户购物体验。",
    company: "fastctl.ai",
    country: "日本",
    category: "Search",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://fastctl.ai/",
    logo: getLogoUrl("fastctl.ai"),
  },
  {
    id: "408",
    title: "MiiTel 语音AI云服务",
    description: "一个基于AI的语音分析云电话服务，能够实时转录和分析销售及客服通话，提供可视化数据以优化沟通。",
    company: "RevComm",
    country: "日本",
    category: "Audio",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://www.revcomm.co.jp/",
    logo: getLogoUrl("RevComm"),
  },
  {
    id: "409",
    title: "Anews 商业决策平台",
    description: "一个利用AI进行文本挖掘的商业决策支持平台，帮助企业从海量新闻和报告中自动发现关键业务信息。",
    company: "StockMark",
    country: "日本",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2017-01-01",
    link: "https://stockmark.co.jp/",
    logo: getLogoUrl("StockMark"),
  },
  {
    id: "500",
    title: "AI驱动的人口健康管理解决方案",
    description: "帮助医疗机构通过AI分析患者数据以管理人群健康。",
    company: "Persistent Systems",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://www.persistent.com/industries/healthcare/population-health-management/",
    logo: getLogoUrl("Persistent Systems"),
  },
  {
    id: "501",
    title: "AI驾驶员监控系统",
    description: "使用AI监控驾驶员行为和警觉性，提高道路安全。",
    company: "Tata Elxsi",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2021-01-01",
    link: "https://www.tataelxsi.com/industries/transportation/autonomous-driving",
    logo: getLogoUrl("Tata Elxsi"),
  },
  {
    id: "502",
    title: "制造业AI预测性维护",
    description: "使用AI预测制造设备故障，减少停机时间。",
    company: "Bosch Limited",
    parentCompany: "Bosch",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://www.bosch.in/our-business/industrial-technology/",
    logo: getLogoUrl("Bosch Limited"),
  },
  {
    id: "503",
    title: "银行AI欺诈检测",
    description: "通过AI分析交易数据以识别潜在欺诈。",
    company: "Oracle Financial Services Software Limited",
    parentCompany: "Oracle",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://www.oracle.com/industries/financial-services/analytics/fraud-detection/",
    logo: getLogoUrl("Oracle Financial Services Software Limited"),
  },
  {
    id: "504",
    title: "AI驱动的分析平台",
    description: "为消费者洞察和风险管理提供AI驱动的分析。",
    company: "Fractal Analytics",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2015-01-01",
    link: "https://fractal.ai/",
    logo: getLogoUrl("Fractal Analytics"),
  },
  {
    id: "505",
    title: "自主AI系统",
    description: "提供自主AI系统和深度学习解决方案。",
    company: "Arya.ai",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2016-01-01",
    link: "https://arya.ai/",
    logo: getLogoUrl("Arya.ai"),
  },
  {
    id: "506",
    title: "零售与电商AI平台",
    description: "为零售和电子商务提供AI平台。",
    company: "Mad Street Den",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2015-01-01",
    link: "https://www.madstreetden.com/",
    logo: getLogoUrl("Mad Street Den"),
  },
  {
    id: "507",
    title: "对话式AI平台",
    description: "为客户服务提供对话式AI平台。",
    company: "Yellow.ai",
    country: "印度",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2016-01-01",
    link: "https://yellow.ai/",
    logo: getLogoUrl("Yellow.ai"),
  },
  {
    id: "605",
    title: "Bow IPU",
    description: "Graphcore最新一代的智能处理单元（IPU），专为机器学习和大语言模型设计，加速AI计算。",
    company: "Graphcore",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2022-01-01",
    link: "https://www.graphcore.ai/",
    logo: getLogoUrl("Graphcore"),
  },
  {
    id: "607",
    title: "Vault Platform",
    description: "Thought Machine开发的云原生核心银行系统，通过API集成AI功能，优化银行产品管理。",
    company: "Thought Machine",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2016-01-01",
    link: "https://www.thoughtmachine.net/",
    logo: getLogoUrl("Thought Machine"),
  },
  {
    id: "608",
    title: "Contextual Decision Intelligence (CDI)",
    description: "Quantexa开发的机器学习平台，分析多源数据以识别非法活动（如洗钱）。",
    company: "Quantexa",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2016-01-01",
    link: "https://www.quantexa.com/",
    logo: getLogoUrl("Quantexa"),
  },
  {
    id: "609",
    title: "Babylon App",
    description: "Babylon Health开发的AI聊天机器人，通过症状分析提供医疗建议，并支持远程医生咨询。",
    company: "Babylon Health",
    country: "英国",
    category: "Platform",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2014-01-01",
    link: "https://www.babylonhealth.com/",
    logo: getLogoUrl("Babylon Health"),
  },
  {
    id: "610",
    title: "DreamStudio",
    description: "基于Stable Diffusion的商业化平台，用于从文本生成高质量图像。",
    company: "Stability AI",
    country: "英国",
    category: "Image Generation",
    type: "Product",
    pricing: "免费增值",
    version: "",
    date: "2022-01-01",
    link: "https://beta.dreamstudio.ai/",
    logo: getLogoUrl("Stability AI"),
  },
  {
    id: "611",
    title: "Evolution AI Platform",
    description: "从PDF、扫描件和电子文本中提取数据的AI工具，应用于金融和企业。",
    company: "Evolution AI",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://www.evolution.ai/",
    logo: getLogoUrl("Evolution AI"),
  },
  {
    id: "612",
    title: "Oxa MetaDriver",
    description: "Oxa (原Oxbotica) 开发的自动驾驶软件，使用AI优化路径规划和决策。",
    company: "Oxa",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://oxa.ai/",
    logo: getLogoUrl("Oxa"),
  },
  {
    id: "614",
    title: "Crystal",
    description: "iGenius开发的AI虚拟顾问，简化数据分析和商业智能决策。",
    company: "iGenius",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2016-01-01",
    link: "https://igenius.ai/",
    logo: getLogoUrl("iGenius"),
  },
  {
    id: "615",
    title: "Conversational AI Platform",
    description: "PolyAI开发的语音助手技术，支持自然对话，应用于客户服务。",
    company: "PolyAI",
    country: "英国",
    category: "Audio",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2020-01-01",
    link: "https://poly.ai/",
    logo: getLogoUrl("PolyAI"),
  },
  {
    id: "616",
    title: "AI Underwriting System",
    description: "Lendable利用AI优化的贷款审批系统，自动化并加速决策。",
    company: "Lendable",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2014-01-01",
    link: "https://www.lendable.co.uk/",
    logo: getLogoUrl("Lendable"),
  },
  {
    id: "617",
    title: "Fetch.ai Agent Market",
    description: "开发AI代理市场，应用于去中心化金融和智能电网。",
    company: "Fetch.ai",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2023-01-01",
    link: "https://fetch.ai/",
    logo: getLogoUrl("Fetch.ai"),
  },
  {
    id: "618",
    title: "Patsnap AI Patent Analysis",
    description: "一个AI驱动的专利分析平台，服务于科技企业。",
    company: "Patsnap",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2015-01-01",
    link: "https://www.patsnap.com/",
    logo: getLogoUrl("Patsnap"),
  },
  {
    id: "619",
    title: "SignalAI Media Monitoring",
    description: "一款AI媒体监控工具，帮助企业追踪品牌声誉和市场动态。",
    company: "SignalAI",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2015-01-01",
    link: "https://www.signal-ai.com/",
    logo: getLogoUrl("SignalAI"),
  },
  {
    id: "620",
    title: "Dexory Warehouse Management Robots",
    description: "一个AI驱动的仓库管理机器人和软件平台，用于库存盘点和空间优化。",
    company: "Dexory",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2017-01-01",
    link: "https://www.dexory.com/",
    logo: getLogoUrl("Dexory"),
  },
  {
    id: "621",
    title: "Manas AI Prediction Platform",
    description: "一个跨行业的预测平台，利用AI帮助企业进行需求预测和风险管理。",
    company: "Manas AI",
    country: "英国",
    category: "Platform",
    type: "Service",
    pricing: "商业",
    version: "",
    date: "2018-01-01",
    link: "https://www.manas.ai/",
    logo: getLogoUrl("Manas AI"),
  },
];

    