
// This file is auto-generated by a script. Do not edit manually.
export interface MovieHeavenItem {
  title: string;
  download_links: string[];
  imdb_score?: string;
  category?: string;
  content?: string;
}

// Data sourced from local JSON file.
export const movieHeavenData: MovieHeavenItem[] = [
  {
    "title": "我的牛津岁月/My Oxford Year",
    "download_links": [
      "magnet:?xt=urn:btih:9b27d647e9aa13d09f82d166cf83378bd5802ff8&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e6%88%91%e7%9a%84%e7%89%9b%e6%b4%a5%e5%b2%81%e6%9c%88.2025.BD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.1",
    "category": "剧情/喜剧/爱情",
    "content": "剧情/喜剧/爱情"
  },
  {
    "title": "缉盗/Never a Thief",
    "download_links": [
      "magnet:?xt=urn:btih:ccfa23a443e4350ce1049e30767506df0fa2f257&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e7%bc%89%e7%9b%97.2025.HD.4K.%e5%9b%bd%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "category": "剧情/犯罪",
    "content": "剧情/犯罪"
  },
  {
    "title": "高尔夫球也疯狂2/球场古惑仔2",
    "download_links": [
      "magnet:?xt=urn:btih:ffb6748c054e99d44bc445805f8d49adf01150fa&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e9%ab%98%e5%b0%94%e5%a4%ab%e7%90%83%e4%b9%9f%e7%96%af%e7%8b%822.2025.BD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.5",
    "category": "喜剧/运动",
    "content": "故事，他参加了一场高级高尔夫巡回赛。"
  },
  {
    "title": "侏罗纪世界：重生/侏罗纪世界4/Jurassic World 4",
    "download_links": [
      "magnet:?xt=urn:btih:ddd0096c8e09e849807d0833b106d2a468581c61&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e4%be%8f%e7%bd%97%e7%ba%aa%e4%b8%96%e7%95%8c%ef%bc%9a%e9%87%8d%e7%94%9f.2025.HD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.2",
    "category": "动作/科幻/惊悚/冒险",
    "content": "故事发生在《侏罗纪世界3》事件的五年后。危在旦夕的恐龙族群生存于孤岛之上，但是它们中却隐藏着能够带来人类医药奇迹的关键基因，为获取神秘基因，一支精英小队潜入恐龙禁地，然而等待他们的却是无法预知的危机和惊天阴谋……"
  },
  {
    "title": "永生守卫2/不死军团2(港/台)/老卫兵",
    "download_links": [
      "magnet:?xt=urn:btih:619a72cfc85a00d56a01e93aa0627595a43760c2&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e6%b0%b8%e7%94%9f%e5%ae%88%e5%8d%ab2.2025.BD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "5.4",
    "category": "动作/惊悚/奇幻/冒险"
  },
  {
    "title": "惊变28年/28年后(港)/28年毁灭倒数(台)",
    "download_links": [
      "magnet:?xt=urn:btih:845e26715df66f1bd5ceb973e61bbac27852bda5&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e6%83%8a%e5%8f%9828%e5%b9%b4.2025.BD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "7.1",
    "category": "科幻/惊悚/恐怖"
  },
  {
    "title": "回声谷/回音谷",
    "download_links": [
      "magnet:?xt=urn:btih:c2fb30fa182ce185c007092a02e98b3d8a4e5763&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e5%9b%9e%e5%a3%b0%e8%b0%b7.2025.BD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "category": "剧情/惊悚",
    "content": "剧情/惊悚"
  },
  {
    "title": "物质主义者/钱财心爱物(港)/实利主义者/天作之合(台)/唯物主义者",
    "download_links": [
      "magnet:?xt=urn:btih:20b41d4f32263706003899d50982f12fa0a91882&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e7%89%a9%e8%b4%a8%e4%b8%bb%e4%b9%89%e8%80%85.2025.HD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.6",
    "category": "喜剧/爱情"
  },
  {
    "title": "疾速追杀：芭蕾杀姬/芭蕾猎杀/芭蕾女杀手/芭蕾杀机/芭蕾舞女/捍卫任务：复仇芭蕾(台)/疾速追杀外传：芭蕾杀姬/杀神John Wick外传：芭蕾杀姬(港)",
    "download_links": [
      "magnet:?xt=urn:btih:7487965b0449aa05a3e73944aab06f66eec2e14e&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e7%96%be%e9%80%9f%e8%bf%bd%e6%9d%80%ef%bc%9a%e8%8a%ad%e8%95%be%e6%9d%80%e5%a7%ac.2025.HD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "7.2",
    "category": "动作/惊悚"
  },
  {
    "title": "私家侦探/尾随/Behind The Shadows",
    "download_links": [
      "magnet:?xt=urn:btih:45a1c5c1cd104416fc2144543e98ae6271897f7f&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e7%a7%81%e5%ae%b6%e4%be%a6%e6%8e%a2.2025.HD.4K.%e5%9b%bd%e7%b2%a4%e5%8f%8c%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.3",
    "category": "剧情/悬疑/犯罪",
    "content": "剧情/悬疑/犯罪"
  },
  {
    "title": "时间之子/Endless Journey of Love",
    "download_links": [
      "magnet:?xt=urn:btih:d70f7d6196b88f80086f04b6a08d6205071e79a1&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e6%97%b6%e9%97%b4%e4%b9%8b%e5%ad%90.2025.HD.1080P.%e5%9b%bd%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "category": "爱情/动画/奇幻/冒险"
  },
  {
    "title": "寻秘不老泉/不老泉/青春之泉",
    "download_links": [
      "magnet:?xt=urn:btih:07cd60f971e4653ecb4d9fb838188cc8b875b8b7&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e5%af%bb%e7%a7%98%e4%b8%8d%e8%80%81%e6%b3%89.2025.BD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "category": "悬疑/奇幻/冒险"
  },
  {
    "title": "星际宝贝史迪奇/史迪仔(港)/星际宝贝/星际宝贝：史迪奇(台)/星际宝贝真人版",
    "download_links": [
      "magnet:?xt=urn:btih:8fee23550fd2476b41bdb7688d648e9f59b5a411&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e6%98%9f%e9%99%85%e5%ae%9d%e8%b4%9d%e5%8f%b2%e8%bf%aa%e5%a5%87.2025.BD.1080P.%e5%9b%bd%e7%b2%a4%e8%8b%b1%e4%b8%89%e8%af%ad%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.9",
    "category": "喜剧/动作/科幻/奇幻/冒险",
    "content": "故事。"
  },
  {
    "title": "海底小纵队：海啸大危机/海底小纵队大电影3/Octonauts: the Crisis of the Tsunami",
    "download_links": [
      "magnet:?xt=urn:btih:53e42878e863187ec2f05ec6865c919e9bb4a8e3&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e6%b5%b7%e5%ba%95%e5%b0%8f%e7%ba%b5%e9%98%9f%ef%bc%9a%e6%b5%b7%e5%95%b8%e5%a4%a7%e5%8d%b1%e6%9c%ba.2025.HD.1080P.%e5%9b%bd%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "category": "喜剧/科幻/动画/冒险"
  },
  {
    "title": "水饺皇后/湾仔码头/阳光码头/The Dumpling Queen",
    "download_links": [
      "magnet:?xt=urn:btih:6da86106b647ca4580641e7abc01714f9a27b142&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e6%b0%b4%e9%a5%ba%e7%9a%87%e5%90%8e.2025.HD.1080P.%e5%9b%bd%e8%af%ad%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.5",
    "category": "剧情/传记",
    "content": "剧情/传记"
  },
  {
    "title": "雷霆特攻队*/*新复仇者联盟/*The New Avengers/雷霆特工队/雷霆特攻队",
    "download_links": [
      "magnet:?xt=urn:btih:39d7614c650ac2a16f9885cafebf29271500845e&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e9%9b%b7%e9%9c%86%e7%89%b9%e6%94%bb%e9%98%9f.2025.BD.1080P.%e5%9b%bd%e8%8b%b1%e5%8f%8c%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "7.3",
    "category": "剧情/动作/科幻/犯罪/奇幻/冒险",
    "content": "剧情/动作/科幻/犯罪/奇幻/冒险"
  },
  {
    "title": "新干线惊爆倒数/新干线爆炸案(新版)/新干线大爆破/Bullet Train Explosion",
    "download_links": [
      "magnet:?xt=urn:btih:7c04e4c84c49b2490c6fa20f0b30ee0bd9a31fc0&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e6%96%b0%e5%b9%b2%e7%ba%bf%e6%83%8a%e7%88%86%e5%80%92%e6%95%b0.2025.BD.1080P.%e6%97%a5%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.4",
    "category": "剧情/动作/惊悚/犯罪",
    "content": "剧情/动作/惊悚/犯罪"
  },
  {
    "title": "大风杀/大风吹/Trapped",
    "download_links": [
      "magnet:?xt=urn:btih:b48dea4402c173e0bfff6ae1cddb70cbf54b4b88&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e5%a4%a7%e9%a3%8e%e6%9d%80.2025.HD.1080P.%e5%9b%bd%e8%af%ad%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mp4&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.6",
    "category": "剧情/悬疑/犯罪",
    "content": "剧情/悬疑/犯罪"
  },
  {
    "title": "命中罪爱/六个凶手/A Stolen Life/Town Without Pity",
    "download_links": [
      "magnet:?xt=urn:btih:f51e1b0ba5900b1f5976bfdebc34dc6f5a2ef78f&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e5%91%bd%e4%b8%ad%e7%bd%aa%e7%88%b1.2025.HD.4K.%e5%9b%bd%e8%af%ad%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "category": "剧情/悬疑/犯罪",
    "content": "剧情/悬疑/犯罪"
  },
  {
    "title": "战·争/遗军之战/战·役(港)",
    "download_links": [
      "magnet:?xt=urn:btih:e01eb24b3b46bba7a79cb0afa5f9a60a9dc67c61&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e6%88%98%c2%b7%e4%ba%89.2025.BD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "7.5",
    "category": "剧情/动作/战争",
    "content": "剧情/动作/战争"
  },
  {
    "title": "谍网追凶/暗杀指令/复仇反击战(港/台)/复仇行动/生手/外行/新暗杀指令/业余特工/Operation Revenge",
    "download_links": [
      "magnet:?xt=urn:btih:80f8dd986e47f989f1803cc85e2291d36d363929&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e8%b0%8d%e7%bd%91%e8%bf%bd%e5%87%b6.2025.BD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.6",
    "category": "动作/惊悚"
  },
  {
    "title": "我的世界大电影/当个创世神/我的世界/Minecraft/MINECRAFT：我的世界大电影(港)/MINECRAFT麦块电影(台)",
    "download_links": [
      "magnet:?xt=urn:btih:3667151f4e3779bc9bec0b0757fa51feb8b21518&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e6%88%91%e7%9a%84%e4%b8%96%e7%95%8c%e5%a4%a7%e7%94%b5%e5%bd%b1.2024.BD.1080P.%e5%9b%bd%e8%8b%b1%e5%8f%8c%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "5.7",
    "category": "喜剧/动作/家庭/奇幻/冒险"
  },
  {
    "title": "向阳·花/出狱女子的故事/We Girls",
    "download_links": [
      "magnet:?xt=urn:btih:ac25299dc546b9857bc1d48c4d645fbd79fba706&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e5%90%91%e9%98%b3%c2%b7%e8%8a%b1.2025.HD.1080P.%e5%9b%bd%e8%af%ad%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "8.6",
    "category": "剧情/犯罪",
    "content": "故事/We Girls"
  },
  {
    "title": "制暴：无限杀机/打工汉/打工人/打工仔/工神救援/建筑师/莱文的交易/重裝制裁(台)/Levon Cade/Levon's Trade",
    "download_links": [
      "magnet:?xt=urn:btih:8db53d3bde467bd336426ab9d79517a1f48c5c0b&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e5%88%b6%e6%9a%b4%ef%bc%9a%e6%97%a0%e9%99%90%e6%9d%80%e6%9c%ba.2025.1080P.%e5%9b%bd%e8%8b%b1%e5%8f%8c%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "5.7",
    "category": "动作/惊悚"
  },
  {
    "title": "生命清单/The Life List",
    "download_links": [
      "magnet:?xt=urn:btih:94e02fed0fb0e32efc77fc2c1fbcaad170e5e278&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e7%94%9f%e5%91%bd%e6%b8%85%e5%8d%95.2025.BD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "7.0",
    "category": "剧情/喜剧/爱情",
    "content": "剧情/喜剧/爱情"
  },
  {
    "title": "终极对弈/竞赛/升武/胜负",
    "download_links": [
      "magnet:?xt=urn:btih:1bddcdfd017c1c82080b29fb2f4902990421006f&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e7%bb%88%e6%9e%81%e5%af%b9%e5%bc%88.2025.BD.1080P.%e9%9f%a9%e8%af%ad%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.9",
    "category": "剧情",
    "content": "剧情"
  },
  {
    "title": "非标准恋爱/女巨人也要谈恋爱/女巨人也要谈恋爱电影版/Tall Girl",
    "download_links": [
      "magnet:?xt=urn:btih:e8b9c8da7c1cc811a74dc8595c51b6bd520150a9&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e9%9d%9e%e6%a0%87%e5%87%86%e6%81%8b%e7%88%b1.2025.HD.4K.%e5%9b%bd%e8%af%ad%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "category": "喜剧/爱情",
    "content": "故事。"
  },
  {
    "title": "无痛凯恩/无痛侠(港)/无痛先生(台)",
    "download_links": [
      "magnet:?xt=urn:btih:99582f687e8a652d4a680d9cb06c654ec0afe96b&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e6%97%a0%e7%97%9b%e5%87%af%e6%81%a9.2025.BD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.6",
    "category": "喜剧/动作/惊悚"
  },
  {
    "title": "多幸运遇见你/吹过你吹过的风/教师日记 中国版/Love Island/The Wind That You Blew",
    "download_links": [
      "magnet:?xt=urn:btih:5dc88e4de0b4b4976d0a9555ff805d2696f8db86&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e5%a4%9a%e5%b9%b8%e8%bf%90%e9%81%87%e8%a7%81%e4%bd%a0.2025.HD.4K.%e5%9b%bd%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "category": "剧情/喜剧/爱情",
    "content": "剧情/喜剧/爱情"
  },
  {
    "title": "怪猴/安娜贝尔衍生片/猴(港)/猴子/敲锣猴子/乔利黑猩猩/史蒂芬金之猴子(台)/嗜血怪猴",
    "download_links": [
      "magnet:?xt=urn:btih:8dcf8ac54fa35dd13d8bf777a7e6330262b4e1cc&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e6%80%aa%e7%8c%b4.2025.HD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.3",
    "category": "喜剧/恐怖"
  },
  {
    "title": "美国队长4/美队4/美国队长：无畏新世界(台)/美国队长4：新世界秩序/美国队长4：勇敢新世界(港)",
    "download_links": [
      "magnet:?xt=urn:btih:cdf969b2aa40f6d1e9fc5004822218a982970a6c&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e7%be%8e%e5%9b%bd%e9%98%9f%e9%95%bf4.2025.BD.1080P.%e5%9b%bd%e8%8b%b1%e5%8f%8c%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "5.7",
    "category": "动作/科幻/冒险"
  },
  {
    "title": "唐探1900/唐人街探案1900/唐人街探案前传/唐探前传/Detective Chinatown 1900",
    "download_links": [
      "magnet:?xt=urn:btih:368ad2a24368547f426a0c05b2d99b73bdbce370&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e5%94%90%e6%8e%a21900.2025.BD.1080P.%e5%9b%bd%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.0",
    "category": "喜剧/动作/悬疑"
  },
  {
    "title": "熊出没·重启未来/熊出没：重启未来/熊出没大电影11/Boonie Bears: Future Reborn",
    "download_links": [
      "magnet:?xt=urn:btih:ce57255fe374a51b115c88dcc6bcaf2347b56c27&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e7%86%8a%e5%87%ba%e6%b2%a1%c2%b7%e9%87%8d%e5%90%af%e6%9c%aa%e6%9d%a5.2025.HD.1080P.%e5%9b%bd%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "category": "剧情/喜剧/科幻/动画",
    "content": "剧情/喜剧/科幻/动画"
  },
  {
    "title": "哪吒之魔童闹海/哪吒2/哪吒2之魔童闹海/Ne Zha 2",
    "download_links": [
      "magnet:?xt=urn:btih:4795f5bea979e3ac2c5c96c9c0f80fde49fadace&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e5%93%aa%e5%90%92%e4%b9%8b%e9%ad%94%e7%ab%a5%e9%97%b9%e6%b5%b7.2025.HD.1080P.%e5%9b%bd%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "8.1",
    "category": "剧情/喜剧/动画/奇幻",
    "content": "剧情/喜剧/动画/奇幻"
  },
  {
    "title": "黑修女们/黑祭司2：暗黑修女(台)/黑色修女/女版黑祭司们/驱魔黑修女(港)",
    "download_links": [
      "magnet:?xt=urn:btih:e8882225c8429e5c6cd4804541923c297db321f3&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e9%bb%91%e4%bf%ae%e5%a5%b3%e4%bb%ac.2025.BD.1080P.%e9%9f%a9%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "5.3",
    "category": "剧情/恐怖",
    "content": "剧情/恐怖"
  },
  {
    "title": "丑陋的继姐/Cinderella's Stepsister/The Ugly Stepsister",
    "download_links": [
      "magnet:?xt=urn:btih:1e8a49827c32c5ac3f9f48e016d3a7902251c451&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e4%b8%91%e9%99%8b%e7%9a%84%e7%bb%a7%e5%a7%90.2025.BD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "7.0",
    "category": "剧情/恐怖",
    "content": "剧情/恐怖"
  },
  {
    "title": "绝密战境/极盗战2(台)/极盗战线/贼巢2：绝密战境/贼斗2(港)/钻石大劫案：极盗战(台)",
    "download_links": [
      "magnet:?xt=urn:btih:5ddec57a845714f45a7dd919e198671ad0bd33d6&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e8%b4%bc%e5%b7%a22%ef%bc%9a%e7%bb%9d%e5%af%86%e6%88%98%e5%a2%83.2025.BD.1080P.%e4%b8%ad%e8%8b%b1%e5%8f%8c%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.3",
    "category": "动作/惊悚/犯罪"
  },
  {
    "title": "禁忌童话/成人童话/童话睇硬了(港)/这是一个童话，但却是个请求",
    "download_links": [
      "magnet:?xt=urn:btih:0c50d3097efdfb3da45c01b13822de19c8f8dca3&dn=%e9%98%b3%e5%85%89%e7%94%b5%e5%bd%b1dygod.org.%e7%a6%81%e5%bf%8c%e7%ab%a5%e8%af%9d.2024.BD.1080P.%e9%9f%a9%e8%af%ad%e4%b8%ad%e5%ad%97.mkv&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce"
    ],
    "imdb_score": "6.0",
    "category": "喜剧",
    "content": "故事作家（朴智炫 饰演）故事，毕业后梦想写儿童故事，但被分配到青少年保护队，被迫每天看色情片。更糟糕的是，他被迫写一部成人网络小说。"
  }
]
